Attribute VB_Name = "DGEXPSTB"
'05Mar07 PJC Stub Module Written for the DRUGEXP.BAS for Capio Interface.

Option Explicit
DefInt A-Z

Sub ClearDrugExportHeap()
'05Mar07 PJC Stub

End Sub

Function DrugExportEnabled() As Integer
'05Mar07 PJC Stub
         
End Function

Sub ExportAllDrugs()
'05Mar07 PJC Stub

End Sub

Sub OutputDrug(d As DrugParameters, ByVal blnNewDrug As Integer, blnExportSuccess As Integer)
'05Mar07 PJC Stub

End Sub

