#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1008
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Unit_Test_Base_Data_Layer
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="UHBServiceTestDB")]
	public partial class TestDBDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertSiteProductData(SiteProductData instance);
    partial void UpdateSiteProductData(SiteProductData instance);
    partial void DeleteSiteProductData(SiteProductData instance);
    partial void InsertProductStockInfo(ProductStockInfo instance);
    partial void UpdateProductStockInfo(ProductStockInfo instance);
    partial void DeleteProductStockInfo(ProductStockInfo instance);
    partial void InsertSite(Site instance);
    partial void UpdateSite(Site instance);
    partial void DeleteSite(Site instance);
    #endregion
		
		public TestDBDataContext() : 
				base(global::Unit_Test_Base_Data_Layer.Properties.Settings.Default.UHBServiceTestDBConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public TestDBDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public TestDBDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public TestDBDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public TestDBDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<SiteProductData> SiteProductDatas
		{
			get
			{
				return this.GetTable<SiteProductData>();
			}
		}
		
		public System.Data.Linq.Table<ProductStockInfo> ProductStockInfos
		{
			get
			{
				return this.GetTable<ProductStockInfo>();
			}
		}
		
		public System.Data.Linq.Table<Site> Sites
		{
			get
			{
				return this.GetTable<Site>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="sys.spResetDBForSessionLockerTests")]
		public int spResetDBForSessionLockerTests()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="sys.spResetDBForBaseRowTests")]
		public int spResetDBForBaseRowTests()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="sys.spResetDBForBaseReportingTableTests")]
		public int spResetDBForBaseReportingTableTests()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="sys.spClearDB")]
		public int spClearDB()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((int)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="sys.SiteProductData")]
	public partial class SiteProductData : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _barcode;
		
		private string _siscode;
		
		private string _code;
		
		private string _labeldescription;
		
		private string _tradename;
		
		private string _printformv;
		
		private string _storesdescription;
		
		private System.Nullable<int> _convfact;
		
		private System.Nullable<float> _mlsperpack;
		
		private System.Nullable<char> _cyto;
		
		private string _warcode;
		
		private string _warcode2;
		
		private string _inscode;
		
		private System.Nullable<double> _DosesperIssueUnit;
		
		private string _DosingUnits;
		
		private string _DPSForm;
		
		private int _DrugID;
		
		private System.Nullable<bool> _LabelInIssueUnits;
		
		private System.Nullable<bool> _CanUseSpoon;
		
		private System.Nullable<int> _DSSMasterSiteID;
		
		private int _SiteProductDataID;
		
		private string _BNF;
		
		private System.Nullable<int> _ProductID;
		
		private System.Nullable<double> _MinDailyDose;
		
		private System.Nullable<double> _MaxDailyDose;
		
		private System.Nullable<double> _MinDoseFrequency;
		
		private System.Nullable<double> _MaxDoseFrequency;
		
		private bool _warcode_Locked;
		
		private bool _warcode2_Locked;
		
		private bool _inscode_Locked;
		
		private bool _StoresDescription_Locked;
		
		private bool _LabelDescription_Locked;
		
		private int @__RowVersion;
		
		private System.Guid @__RowGUID;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnbarcodeChanging(string value);
    partial void OnbarcodeChanged();
    partial void OnsiscodeChanging(string value);
    partial void OnsiscodeChanged();
    partial void OncodeChanging(string value);
    partial void OncodeChanged();
    partial void OnlabeldescriptionChanging(string value);
    partial void OnlabeldescriptionChanged();
    partial void OntradenameChanging(string value);
    partial void OntradenameChanged();
    partial void OnprintformvChanging(string value);
    partial void OnprintformvChanged();
    partial void OnstoresdescriptionChanging(string value);
    partial void OnstoresdescriptionChanged();
    partial void OnconvfactChanging(System.Nullable<int> value);
    partial void OnconvfactChanged();
    partial void OnmlsperpackChanging(System.Nullable<float> value);
    partial void OnmlsperpackChanged();
    partial void OncytoChanging(System.Nullable<char> value);
    partial void OncytoChanged();
    partial void OnwarcodeChanging(string value);
    partial void OnwarcodeChanged();
    partial void Onwarcode2Changing(string value);
    partial void Onwarcode2Changed();
    partial void OninscodeChanging(string value);
    partial void OninscodeChanged();
    partial void OnDosesperIssueUnitChanging(System.Nullable<double> value);
    partial void OnDosesperIssueUnitChanged();
    partial void OnDosingUnitsChanging(string value);
    partial void OnDosingUnitsChanged();
    partial void OnDPSFormChanging(string value);
    partial void OnDPSFormChanged();
    partial void OnDrugIDChanging(int value);
    partial void OnDrugIDChanged();
    partial void OnLabelInIssueUnitsChanging(System.Nullable<bool> value);
    partial void OnLabelInIssueUnitsChanged();
    partial void OnCanUseSpoonChanging(System.Nullable<bool> value);
    partial void OnCanUseSpoonChanged();
    partial void OnDSSMasterSiteIDChanging(System.Nullable<int> value);
    partial void OnDSSMasterSiteIDChanged();
    partial void OnSiteProductDataIDChanging(int value);
    partial void OnSiteProductDataIDChanged();
    partial void OnBNFChanging(string value);
    partial void OnBNFChanged();
    partial void OnProductIDChanging(System.Nullable<int> value);
    partial void OnProductIDChanged();
    partial void OnMinDailyDoseChanging(System.Nullable<double> value);
    partial void OnMinDailyDoseChanged();
    partial void OnMaxDailyDoseChanging(System.Nullable<double> value);
    partial void OnMaxDailyDoseChanged();
    partial void OnMinDoseFrequencyChanging(System.Nullable<double> value);
    partial void OnMinDoseFrequencyChanged();
    partial void OnMaxDoseFrequencyChanging(System.Nullable<double> value);
    partial void OnMaxDoseFrequencyChanged();
    partial void Onwarcode_LockedChanging(bool value);
    partial void Onwarcode_LockedChanged();
    partial void Onwarcode2_LockedChanging(bool value);
    partial void Onwarcode2_LockedChanged();
    partial void Oninscode_LockedChanging(bool value);
    partial void Oninscode_LockedChanged();
    partial void OnStoresDescription_LockedChanging(bool value);
    partial void OnStoresDescription_LockedChanged();
    partial void OnLabelDescription_LockedChanging(bool value);
    partial void OnLabelDescription_LockedChanged();
    partial void On_RowVersionChanging(int value);
    partial void On_RowVersionChanged();
    partial void On_RowGUIDChanging(System.Guid value);
    partial void On_RowGUIDChanged();
    #endregion
		
		public SiteProductData()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_barcode", DbType="VarChar(13)")]
		public string barcode
		{
			get
			{
				return this._barcode;
			}
			set
			{
				if ((this._barcode != value))
				{
					this.OnbarcodeChanging(value);
					this.SendPropertyChanging();
					this._barcode = value;
					this.SendPropertyChanged("barcode");
					this.OnbarcodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_siscode", DbType="VarChar(7)")]
		public string siscode
		{
			get
			{
				return this._siscode;
			}
			set
			{
				if ((this._siscode != value))
				{
					this.OnsiscodeChanging(value);
					this.SendPropertyChanging();
					this._siscode = value;
					this.SendPropertyChanged("siscode");
					this.OnsiscodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_code", DbType="VarChar(8)")]
		public string code
		{
			get
			{
				return this._code;
			}
			set
			{
				if ((this._code != value))
				{
					this.OncodeChanging(value);
					this.SendPropertyChanging();
					this._code = value;
					this.SendPropertyChanged("code");
					this.OncodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_labeldescription", DbType="VarChar(56)")]
		public string labeldescription
		{
			get
			{
				return this._labeldescription;
			}
			set
			{
				if ((this._labeldescription != value))
				{
					this.OnlabeldescriptionChanging(value);
					this.SendPropertyChanging();
					this._labeldescription = value;
					this.SendPropertyChanged("labeldescription");
					this.OnlabeldescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tradename", DbType="VarChar(30)")]
		public string tradename
		{
			get
			{
				return this._tradename;
			}
			set
			{
				if ((this._tradename != value))
				{
					this.OntradenameChanging(value);
					this.SendPropertyChanging();
					this._tradename = value;
					this.SendPropertyChanged("tradename");
					this.OntradenameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_printformv", DbType="VarChar(5)")]
		public string printformv
		{
			get
			{
				return this._printformv;
			}
			set
			{
				if ((this._printformv != value))
				{
					this.OnprintformvChanging(value);
					this.SendPropertyChanging();
					this._printformv = value;
					this.SendPropertyChanged("printformv");
					this.OnprintformvChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_storesdescription", DbType="VarChar(56)")]
		public string storesdescription
		{
			get
			{
				return this._storesdescription;
			}
			set
			{
				if ((this._storesdescription != value))
				{
					this.OnstoresdescriptionChanging(value);
					this.SendPropertyChanging();
					this._storesdescription = value;
					this.SendPropertyChanged("storesdescription");
					this.OnstoresdescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_convfact", DbType="Int")]
		public System.Nullable<int> convfact
		{
			get
			{
				return this._convfact;
			}
			set
			{
				if ((this._convfact != value))
				{
					this.OnconvfactChanging(value);
					this.SendPropertyChanging();
					this._convfact = value;
					this.SendPropertyChanged("convfact");
					this.OnconvfactChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mlsperpack", DbType="Real")]
		public System.Nullable<float> mlsperpack
		{
			get
			{
				return this._mlsperpack;
			}
			set
			{
				if ((this._mlsperpack != value))
				{
					this.OnmlsperpackChanging(value);
					this.SendPropertyChanging();
					this._mlsperpack = value;
					this.SendPropertyChanged("mlsperpack");
					this.OnmlsperpackChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cyto", DbType="VarChar(1)")]
		public System.Nullable<char> cyto
		{
			get
			{
				return this._cyto;
			}
			set
			{
				if ((this._cyto != value))
				{
					this.OncytoChanging(value);
					this.SendPropertyChanging();
					this._cyto = value;
					this.SendPropertyChanged("cyto");
					this.OncytoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_warcode", DbType="VarChar(6)")]
		public string warcode
		{
			get
			{
				return this._warcode;
			}
			set
			{
				if ((this._warcode != value))
				{
					this.OnwarcodeChanging(value);
					this.SendPropertyChanging();
					this._warcode = value;
					this.SendPropertyChanged("warcode");
					this.OnwarcodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_warcode2", DbType="VarChar(6)")]
		public string warcode2
		{
			get
			{
				return this._warcode2;
			}
			set
			{
				if ((this._warcode2 != value))
				{
					this.Onwarcode2Changing(value);
					this.SendPropertyChanging();
					this._warcode2 = value;
					this.SendPropertyChanged("warcode2");
					this.Onwarcode2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_inscode", DbType="VarChar(6)")]
		public string inscode
		{
			get
			{
				return this._inscode;
			}
			set
			{
				if ((this._inscode != value))
				{
					this.OninscodeChanging(value);
					this.SendPropertyChanging();
					this._inscode = value;
					this.SendPropertyChanged("inscode");
					this.OninscodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DosesperIssueUnit", DbType="Float")]
		public System.Nullable<double> DosesperIssueUnit
		{
			get
			{
				return this._DosesperIssueUnit;
			}
			set
			{
				if ((this._DosesperIssueUnit != value))
				{
					this.OnDosesperIssueUnitChanging(value);
					this.SendPropertyChanging();
					this._DosesperIssueUnit = value;
					this.SendPropertyChanged("DosesperIssueUnit");
					this.OnDosesperIssueUnitChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DosingUnits", DbType="VarChar(20)")]
		public string DosingUnits
		{
			get
			{
				return this._DosingUnits;
			}
			set
			{
				if ((this._DosingUnits != value))
				{
					this.OnDosingUnitsChanging(value);
					this.SendPropertyChanging();
					this._DosingUnits = value;
					this.SendPropertyChanged("DosingUnits");
					this.OnDosingUnitsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DPSForm", DbType="VarChar(4)")]
		public string DPSForm
		{
			get
			{
				return this._DPSForm;
			}
			set
			{
				if ((this._DPSForm != value))
				{
					this.OnDPSFormChanging(value);
					this.SendPropertyChanging();
					this._DPSForm = value;
					this.SendPropertyChanged("DPSForm");
					this.OnDPSFormChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DrugID", DbType="Int NOT NULL")]
		public int DrugID
		{
			get
			{
				return this._DrugID;
			}
			set
			{
				if ((this._DrugID != value))
				{
					this.OnDrugIDChanging(value);
					this.SendPropertyChanging();
					this._DrugID = value;
					this.SendPropertyChanged("DrugID");
					this.OnDrugIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LabelInIssueUnits", DbType="Bit")]
		public System.Nullable<bool> LabelInIssueUnits
		{
			get
			{
				return this._LabelInIssueUnits;
			}
			set
			{
				if ((this._LabelInIssueUnits != value))
				{
					this.OnLabelInIssueUnitsChanging(value);
					this.SendPropertyChanging();
					this._LabelInIssueUnits = value;
					this.SendPropertyChanged("LabelInIssueUnits");
					this.OnLabelInIssueUnitsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CanUseSpoon", DbType="Bit")]
		public System.Nullable<bool> CanUseSpoon
		{
			get
			{
				return this._CanUseSpoon;
			}
			set
			{
				if ((this._CanUseSpoon != value))
				{
					this.OnCanUseSpoonChanging(value);
					this.SendPropertyChanging();
					this._CanUseSpoon = value;
					this.SendPropertyChanged("CanUseSpoon");
					this.OnCanUseSpoonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DSSMasterSiteID", DbType="Int")]
		public System.Nullable<int> DSSMasterSiteID
		{
			get
			{
				return this._DSSMasterSiteID;
			}
			set
			{
				if ((this._DSSMasterSiteID != value))
				{
					this.OnDSSMasterSiteIDChanging(value);
					this.SendPropertyChanging();
					this._DSSMasterSiteID = value;
					this.SendPropertyChanged("DSSMasterSiteID");
					this.OnDSSMasterSiteIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SiteProductDataID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int SiteProductDataID
		{
			get
			{
				return this._SiteProductDataID;
			}
			set
			{
				if ((this._SiteProductDataID != value))
				{
					this.OnSiteProductDataIDChanging(value);
					this.SendPropertyChanging();
					this._SiteProductDataID = value;
					this.SendPropertyChanged("SiteProductDataID");
					this.OnSiteProductDataIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BNF", DbType="VarChar(13)")]
		public string BNF
		{
			get
			{
				return this._BNF;
			}
			set
			{
				if ((this._BNF != value))
				{
					this.OnBNFChanging(value);
					this.SendPropertyChanging();
					this._BNF = value;
					this.SendPropertyChanged("BNF");
					this.OnBNFChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProductID", DbType="Int")]
		public System.Nullable<int> ProductID
		{
			get
			{
				return this._ProductID;
			}
			set
			{
				if ((this._ProductID != value))
				{
					this.OnProductIDChanging(value);
					this.SendPropertyChanging();
					this._ProductID = value;
					this.SendPropertyChanged("ProductID");
					this.OnProductIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MinDailyDose", DbType="Float")]
		public System.Nullable<double> MinDailyDose
		{
			get
			{
				return this._MinDailyDose;
			}
			set
			{
				if ((this._MinDailyDose != value))
				{
					this.OnMinDailyDoseChanging(value);
					this.SendPropertyChanging();
					this._MinDailyDose = value;
					this.SendPropertyChanged("MinDailyDose");
					this.OnMinDailyDoseChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaxDailyDose", DbType="Float")]
		public System.Nullable<double> MaxDailyDose
		{
			get
			{
				return this._MaxDailyDose;
			}
			set
			{
				if ((this._MaxDailyDose != value))
				{
					this.OnMaxDailyDoseChanging(value);
					this.SendPropertyChanging();
					this._MaxDailyDose = value;
					this.SendPropertyChanged("MaxDailyDose");
					this.OnMaxDailyDoseChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MinDoseFrequency", DbType="Float")]
		public System.Nullable<double> MinDoseFrequency
		{
			get
			{
				return this._MinDoseFrequency;
			}
			set
			{
				if ((this._MinDoseFrequency != value))
				{
					this.OnMinDoseFrequencyChanging(value);
					this.SendPropertyChanging();
					this._MinDoseFrequency = value;
					this.SendPropertyChanged("MinDoseFrequency");
					this.OnMinDoseFrequencyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaxDoseFrequency", DbType="Float")]
		public System.Nullable<double> MaxDoseFrequency
		{
			get
			{
				return this._MaxDoseFrequency;
			}
			set
			{
				if ((this._MaxDoseFrequency != value))
				{
					this.OnMaxDoseFrequencyChanging(value);
					this.SendPropertyChanging();
					this._MaxDoseFrequency = value;
					this.SendPropertyChanged("MaxDoseFrequency");
					this.OnMaxDoseFrequencyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_warcode_Locked", DbType="Bit NOT NULL")]
		public bool warcode_Locked
		{
			get
			{
				return this._warcode_Locked;
			}
			set
			{
				if ((this._warcode_Locked != value))
				{
					this.Onwarcode_LockedChanging(value);
					this.SendPropertyChanging();
					this._warcode_Locked = value;
					this.SendPropertyChanged("warcode_Locked");
					this.Onwarcode_LockedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_warcode2_Locked", DbType="Bit NOT NULL")]
		public bool warcode2_Locked
		{
			get
			{
				return this._warcode2_Locked;
			}
			set
			{
				if ((this._warcode2_Locked != value))
				{
					this.Onwarcode2_LockedChanging(value);
					this.SendPropertyChanging();
					this._warcode2_Locked = value;
					this.SendPropertyChanged("warcode2_Locked");
					this.Onwarcode2_LockedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_inscode_Locked", DbType="Bit NOT NULL")]
		public bool inscode_Locked
		{
			get
			{
				return this._inscode_Locked;
			}
			set
			{
				if ((this._inscode_Locked != value))
				{
					this.Oninscode_LockedChanging(value);
					this.SendPropertyChanging();
					this._inscode_Locked = value;
					this.SendPropertyChanged("inscode_Locked");
					this.Oninscode_LockedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StoresDescription_Locked", DbType="Bit NOT NULL")]
		public bool StoresDescription_Locked
		{
			get
			{
				return this._StoresDescription_Locked;
			}
			set
			{
				if ((this._StoresDescription_Locked != value))
				{
					this.OnStoresDescription_LockedChanging(value);
					this.SendPropertyChanging();
					this._StoresDescription_Locked = value;
					this.SendPropertyChanged("StoresDescription_Locked");
					this.OnStoresDescription_LockedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LabelDescription_Locked", DbType="Bit NOT NULL")]
		public bool LabelDescription_Locked
		{
			get
			{
				return this._LabelDescription_Locked;
			}
			set
			{
				if ((this._LabelDescription_Locked != value))
				{
					this.OnLabelDescription_LockedChanging(value);
					this.SendPropertyChanging();
					this._LabelDescription_Locked = value;
					this.SendPropertyChanged("LabelDescription_Locked");
					this.OnLabelDescription_LockedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[_RowVersion]", Storage="__RowVersion", DbType="Int NOT NULL")]
		public int _RowVersion
		{
			get
			{
				return this.@__RowVersion;
			}
			set
			{
				if ((this.@__RowVersion != value))
				{
					this.On_RowVersionChanging(value);
					this.SendPropertyChanging();
					this.@__RowVersion = value;
					this.SendPropertyChanged("_RowVersion");
					this.On_RowVersionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[_RowGUID]", Storage="__RowGUID", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid _RowGUID
		{
			get
			{
				return this.@__RowGUID;
			}
			set
			{
				if ((this.@__RowGUID != value))
				{
					this.On_RowGUIDChanging(value);
					this.SendPropertyChanging();
					this.@__RowGUID = value;
					this.SendPropertyChanged("_RowGUID");
					this.On_RowGUIDChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="sys.ProductStock")]
	public partial class ProductStockInfo : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ProductStockID;
		
		private int _ProductID;
		
		private int _LocationID_Site;
		
		private char _inuse;
		
		private char _cyto;
		
		private char _formulary;
		
		private string _warcode;
		
		private string _warcode2;
		
		private string _inscode;
		
		private string _dircode;
		
		private System.Nullable<char> _labelformat;
		
		private string _extralabel;
		
		private int _expiryminutes;
		
		private string _minissue;
		
		private string _maxissue;
		
		private string _lastissued;
		
		private char _issueWholePack;
		
		private string _stocklvl;
		
		private char _sisstock;
		
		private char _livestockctrl;
		
		private string _ordercycle;
		
		private int _cyclelength;
		
		private double _outstanding;
		
		private string _loccode;
		
		private string _loccode2;
		
		private string _anuse;
		
		private double _usethisperiod;
		
		private char _recalcatperiodend;
		
		private string _datelastperiodend;
		
		private double _usagedamping;
		
		private double _safetyfactor;
		
		private string _supcode;
		
		private string _altsupcode;
		
		private string _contno;
		
		private string _lastordered;
		
		private System.Nullable<char> _stocktakestatus;
		
		private string _laststocktakedate;
		
		private string _laststocktaketime;
		
		private char _batchtracking;
		
		private string _cost;
		
		private double _lossesgains;
		
		private string _ledcode;
		
		private char _pflag;
		
		private string _message;
		
		private string _UserMsg;
		
		private int _PILnumber;
		
		private string _PIL2;
		
		private string _CreatedUser;
		
		private string _createdterminal;
		
		private string _createddate;
		
		private string _createdtime;
		
		private string _modifieduser;
		
		private string _modifiedterminal;
		
		private string _modifieddate;
		
		private string _modifiedtime;
		
		private string _local;
		
		private System.Nullable<double> _ReconVol;
		
		private string _ReconAbbr;
		
		private string _Diluent1;
		
		private string _Diluent2;
		
		private System.Nullable<double> _InfusionTime;
		
		private System.Nullable<double> _Minmgperml;
		
		private System.Nullable<double> _Maxmgperml;
		
		private System.Nullable<char> _IVContainer;
		
		private System.Nullable<double> _DisplacementVolume;
		
		private System.Nullable<double> _mgPerml;
		
		private System.Nullable<double> _maxInfusionRate;
		
		private System.Nullable<char> _CIVAS;
		
		private System.Nullable<int> _convfact;
		
		private System.Nullable<double> _DosesPerIssueUnit;
		
		private string _StoresPack;
		
		private int _SessionLock;
		
		private string _bnf;
		
		private string _Therapcode;
		
		private string _Reorderlvl;
		
		private string _ReorderQty;
		
		private System.Nullable<int> _DrugID;
		
		private EntityRef<Site> _Site;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnProductStockIDChanging(int value);
    partial void OnProductStockIDChanged();
    partial void OnProductIDChanging(int value);
    partial void OnProductIDChanged();
    partial void OnLocationID_SiteChanging(int value);
    partial void OnLocationID_SiteChanged();
    partial void OninuseChanging(char value);
    partial void OninuseChanged();
    partial void OncytoChanging(char value);
    partial void OncytoChanged();
    partial void OnformularyChanging(char value);
    partial void OnformularyChanged();
    partial void OnwarcodeChanging(string value);
    partial void OnwarcodeChanged();
    partial void Onwarcode2Changing(string value);
    partial void Onwarcode2Changed();
    partial void OninscodeChanging(string value);
    partial void OninscodeChanged();
    partial void OndircodeChanging(string value);
    partial void OndircodeChanged();
    partial void OnlabelformatChanging(System.Nullable<char> value);
    partial void OnlabelformatChanged();
    partial void OnextralabelChanging(string value);
    partial void OnextralabelChanged();
    partial void OnexpiryminutesChanging(int value);
    partial void OnexpiryminutesChanged();
    partial void OnminissueChanging(string value);
    partial void OnminissueChanged();
    partial void OnmaxissueChanging(string value);
    partial void OnmaxissueChanged();
    partial void OnlastissuedChanging(string value);
    partial void OnlastissuedChanged();
    partial void OnissueWholePackChanging(char value);
    partial void OnissueWholePackChanged();
    partial void OnstocklvlChanging(string value);
    partial void OnstocklvlChanged();
    partial void OnsisstockChanging(char value);
    partial void OnsisstockChanged();
    partial void OnlivestockctrlChanging(char value);
    partial void OnlivestockctrlChanged();
    partial void OnordercycleChanging(string value);
    partial void OnordercycleChanged();
    partial void OncyclelengthChanging(int value);
    partial void OncyclelengthChanged();
    partial void OnoutstandingChanging(double value);
    partial void OnoutstandingChanged();
    partial void OnloccodeChanging(string value);
    partial void OnloccodeChanged();
    partial void Onloccode2Changing(string value);
    partial void Onloccode2Changed();
    partial void OnanuseChanging(string value);
    partial void OnanuseChanged();
    partial void OnusethisperiodChanging(double value);
    partial void OnusethisperiodChanged();
    partial void OnrecalcatperiodendChanging(char value);
    partial void OnrecalcatperiodendChanged();
    partial void OndatelastperiodendChanging(string value);
    partial void OndatelastperiodendChanged();
    partial void OnusagedampingChanging(double value);
    partial void OnusagedampingChanged();
    partial void OnsafetyfactorChanging(double value);
    partial void OnsafetyfactorChanged();
    partial void OnsupcodeChanging(string value);
    partial void OnsupcodeChanged();
    partial void OnaltsupcodeChanging(string value);
    partial void OnaltsupcodeChanged();
    partial void OncontnoChanging(string value);
    partial void OncontnoChanged();
    partial void OnlastorderedChanging(string value);
    partial void OnlastorderedChanged();
    partial void OnstocktakestatusChanging(System.Nullable<char> value);
    partial void OnstocktakestatusChanged();
    partial void OnlaststocktakedateChanging(string value);
    partial void OnlaststocktakedateChanged();
    partial void OnlaststocktaketimeChanging(string value);
    partial void OnlaststocktaketimeChanged();
    partial void OnbatchtrackingChanging(char value);
    partial void OnbatchtrackingChanged();
    partial void OncostChanging(string value);
    partial void OncostChanged();
    partial void OnlossesgainsChanging(double value);
    partial void OnlossesgainsChanged();
    partial void OnledcodeChanging(string value);
    partial void OnledcodeChanged();
    partial void OnpflagChanging(char value);
    partial void OnpflagChanged();
    partial void OnmessageChanging(string value);
    partial void OnmessageChanged();
    partial void OnUserMsgChanging(string value);
    partial void OnUserMsgChanged();
    partial void OnPILnumberChanging(int value);
    partial void OnPILnumberChanged();
    partial void OnPIL2Changing(string value);
    partial void OnPIL2Changed();
    partial void OnCreatedUserChanging(string value);
    partial void OnCreatedUserChanged();
    partial void OncreatedterminalChanging(string value);
    partial void OncreatedterminalChanged();
    partial void OncreateddateChanging(string value);
    partial void OncreateddateChanged();
    partial void OncreatedtimeChanging(string value);
    partial void OncreatedtimeChanged();
    partial void OnmodifieduserChanging(string value);
    partial void OnmodifieduserChanged();
    partial void OnmodifiedterminalChanging(string value);
    partial void OnmodifiedterminalChanged();
    partial void OnmodifieddateChanging(string value);
    partial void OnmodifieddateChanged();
    partial void OnmodifiedtimeChanging(string value);
    partial void OnmodifiedtimeChanged();
    partial void OnlocalChanging(string value);
    partial void OnlocalChanged();
    partial void OnReconVolChanging(System.Nullable<double> value);
    partial void OnReconVolChanged();
    partial void OnReconAbbrChanging(string value);
    partial void OnReconAbbrChanged();
    partial void OnDiluent1Changing(string value);
    partial void OnDiluent1Changed();
    partial void OnDiluent2Changing(string value);
    partial void OnDiluent2Changed();
    partial void OnInfusionTimeChanging(System.Nullable<double> value);
    partial void OnInfusionTimeChanged();
    partial void OnMinmgpermlChanging(System.Nullable<double> value);
    partial void OnMinmgpermlChanged();
    partial void OnMaxmgpermlChanging(System.Nullable<double> value);
    partial void OnMaxmgpermlChanged();
    partial void OnIVContainerChanging(System.Nullable<char> value);
    partial void OnIVContainerChanged();
    partial void OnDisplacementVolumeChanging(System.Nullable<double> value);
    partial void OnDisplacementVolumeChanged();
    partial void OnmgPermlChanging(System.Nullable<double> value);
    partial void OnmgPermlChanged();
    partial void OnmaxInfusionRateChanging(System.Nullable<double> value);
    partial void OnmaxInfusionRateChanged();
    partial void OnCIVASChanging(System.Nullable<char> value);
    partial void OnCIVASChanged();
    partial void OnconvfactChanging(System.Nullable<int> value);
    partial void OnconvfactChanged();
    partial void OnDosesPerIssueUnitChanging(System.Nullable<double> value);
    partial void OnDosesPerIssueUnitChanged();
    partial void OnStoresPackChanging(string value);
    partial void OnStoresPackChanged();
    partial void OnSessionLockChanging(int value);
    partial void OnSessionLockChanged();
    partial void OnbnfChanging(string value);
    partial void OnbnfChanged();
    partial void OnTherapcodeChanging(string value);
    partial void OnTherapcodeChanged();
    partial void OnReorderlvlChanging(string value);
    partial void OnReorderlvlChanged();
    partial void OnReorderQtyChanging(string value);
    partial void OnReorderQtyChanged();
    partial void OnDrugIDChanging(System.Nullable<int> value);
    partial void OnDrugIDChanged();
    #endregion
		
		public ProductStockInfo()
		{
			this._Site = default(EntityRef<Site>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProductStockID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ProductStockID
		{
			get
			{
				return this._ProductStockID;
			}
			set
			{
				if ((this._ProductStockID != value))
				{
					this.OnProductStockIDChanging(value);
					this.SendPropertyChanging();
					this._ProductStockID = value;
					this.SendPropertyChanged("ProductStockID");
					this.OnProductStockIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProductID", DbType="Int NOT NULL")]
		public int ProductID
		{
			get
			{
				return this._ProductID;
			}
			set
			{
				if ((this._ProductID != value))
				{
					this.OnProductIDChanging(value);
					this.SendPropertyChanging();
					this._ProductID = value;
					this.SendPropertyChanged("ProductID");
					this.OnProductIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LocationID_Site", DbType="Int NOT NULL")]
		public int LocationID_Site
		{
			get
			{
				return this._LocationID_Site;
			}
			set
			{
				if ((this._LocationID_Site != value))
				{
					if (this._Site.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnLocationID_SiteChanging(value);
					this.SendPropertyChanging();
					this._LocationID_Site = value;
					this.SendPropertyChanged("LocationID_Site");
					this.OnLocationID_SiteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_inuse", DbType="VarChar(1) NOT NULL")]
		public char inuse
		{
			get
			{
				return this._inuse;
			}
			set
			{
				if ((this._inuse != value))
				{
					this.OninuseChanging(value);
					this.SendPropertyChanging();
					this._inuse = value;
					this.SendPropertyChanged("inuse");
					this.OninuseChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cyto", DbType="VarChar(1) NOT NULL")]
		public char cyto
		{
			get
			{
				return this._cyto;
			}
			set
			{
				if ((this._cyto != value))
				{
					this.OncytoChanging(value);
					this.SendPropertyChanging();
					this._cyto = value;
					this.SendPropertyChanged("cyto");
					this.OncytoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_formulary", DbType="VarChar(1) NOT NULL")]
		public char formulary
		{
			get
			{
				return this._formulary;
			}
			set
			{
				if ((this._formulary != value))
				{
					this.OnformularyChanging(value);
					this.SendPropertyChanging();
					this._formulary = value;
					this.SendPropertyChanged("formulary");
					this.OnformularyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_warcode", DbType="VarChar(6)")]
		public string warcode
		{
			get
			{
				return this._warcode;
			}
			set
			{
				if ((this._warcode != value))
				{
					this.OnwarcodeChanging(value);
					this.SendPropertyChanging();
					this._warcode = value;
					this.SendPropertyChanged("warcode");
					this.OnwarcodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_warcode2", DbType="VarChar(6)")]
		public string warcode2
		{
			get
			{
				return this._warcode2;
			}
			set
			{
				if ((this._warcode2 != value))
				{
					this.Onwarcode2Changing(value);
					this.SendPropertyChanging();
					this._warcode2 = value;
					this.SendPropertyChanged("warcode2");
					this.Onwarcode2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_inscode", DbType="VarChar(6)")]
		public string inscode
		{
			get
			{
				return this._inscode;
			}
			set
			{
				if ((this._inscode != value))
				{
					this.OninscodeChanging(value);
					this.SendPropertyChanging();
					this._inscode = value;
					this.SendPropertyChanged("inscode");
					this.OninscodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dircode", DbType="VarChar(6)")]
		public string dircode
		{
			get
			{
				return this._dircode;
			}
			set
			{
				if ((this._dircode != value))
				{
					this.OndircodeChanging(value);
					this.SendPropertyChanging();
					this._dircode = value;
					this.SendPropertyChanged("dircode");
					this.OndircodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_labelformat", DbType="VarChar(1)")]
		public System.Nullable<char> labelformat
		{
			get
			{
				return this._labelformat;
			}
			set
			{
				if ((this._labelformat != value))
				{
					this.OnlabelformatChanging(value);
					this.SendPropertyChanging();
					this._labelformat = value;
					this.SendPropertyChanged("labelformat");
					this.OnlabelformatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_extralabel", DbType="VarChar(3)")]
		public string extralabel
		{
			get
			{
				return this._extralabel;
			}
			set
			{
				if ((this._extralabel != value))
				{
					this.OnextralabelChanging(value);
					this.SendPropertyChanging();
					this._extralabel = value;
					this.SendPropertyChanged("extralabel");
					this.OnextralabelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_expiryminutes", DbType="Int NOT NULL")]
		public int expiryminutes
		{
			get
			{
				return this._expiryminutes;
			}
			set
			{
				if ((this._expiryminutes != value))
				{
					this.OnexpiryminutesChanging(value);
					this.SendPropertyChanging();
					this._expiryminutes = value;
					this.SendPropertyChanged("expiryminutes");
					this.OnexpiryminutesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_minissue", DbType="VarChar(4) NOT NULL", CanBeNull=false)]
		public string minissue
		{
			get
			{
				return this._minissue;
			}
			set
			{
				if ((this._minissue != value))
				{
					this.OnminissueChanging(value);
					this.SendPropertyChanging();
					this._minissue = value;
					this.SendPropertyChanged("minissue");
					this.OnminissueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maxissue", DbType="VarChar(5) NOT NULL", CanBeNull=false)]
		public string maxissue
		{
			get
			{
				return this._maxissue;
			}
			set
			{
				if ((this._maxissue != value))
				{
					this.OnmaxissueChanging(value);
					this.SendPropertyChanging();
					this._maxissue = value;
					this.SendPropertyChanged("maxissue");
					this.OnmaxissueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lastissued", DbType="VarChar(8)")]
		public string lastissued
		{
			get
			{
				return this._lastissued;
			}
			set
			{
				if ((this._lastissued != value))
				{
					this.OnlastissuedChanging(value);
					this.SendPropertyChanging();
					this._lastissued = value;
					this.SendPropertyChanged("lastissued");
					this.OnlastissuedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_issueWholePack", DbType="VarChar(1) NOT NULL")]
		public char issueWholePack
		{
			get
			{
				return this._issueWholePack;
			}
			set
			{
				if ((this._issueWholePack != value))
				{
					this.OnissueWholePackChanging(value);
					this.SendPropertyChanging();
					this._issueWholePack = value;
					this.SendPropertyChanged("issueWholePack");
					this.OnissueWholePackChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_stocklvl", DbType="VarChar(9) NOT NULL", CanBeNull=false)]
		public string stocklvl
		{
			get
			{
				return this._stocklvl;
			}
			set
			{
				if ((this._stocklvl != value))
				{
					this.OnstocklvlChanging(value);
					this.SendPropertyChanging();
					this._stocklvl = value;
					this.SendPropertyChanged("stocklvl");
					this.OnstocklvlChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sisstock", DbType="VarChar(1) NOT NULL")]
		public char sisstock
		{
			get
			{
				return this._sisstock;
			}
			set
			{
				if ((this._sisstock != value))
				{
					this.OnsisstockChanging(value);
					this.SendPropertyChanging();
					this._sisstock = value;
					this.SendPropertyChanged("sisstock");
					this.OnsisstockChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_livestockctrl", DbType="VarChar(1) NOT NULL")]
		public char livestockctrl
		{
			get
			{
				return this._livestockctrl;
			}
			set
			{
				if ((this._livestockctrl != value))
				{
					this.OnlivestockctrlChanging(value);
					this.SendPropertyChanging();
					this._livestockctrl = value;
					this.SendPropertyChanged("livestockctrl");
					this.OnlivestockctrlChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ordercycle", DbType="VarChar(2)")]
		public string ordercycle
		{
			get
			{
				return this._ordercycle;
			}
			set
			{
				if ((this._ordercycle != value))
				{
					this.OnordercycleChanging(value);
					this.SendPropertyChanging();
					this._ordercycle = value;
					this.SendPropertyChanged("ordercycle");
					this.OnordercycleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cyclelength", DbType="Int NOT NULL")]
		public int cyclelength
		{
			get
			{
				return this._cyclelength;
			}
			set
			{
				if ((this._cyclelength != value))
				{
					this.OncyclelengthChanging(value);
					this.SendPropertyChanging();
					this._cyclelength = value;
					this.SendPropertyChanged("cyclelength");
					this.OncyclelengthChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_outstanding", DbType="Float NOT NULL")]
		public double outstanding
		{
			get
			{
				return this._outstanding;
			}
			set
			{
				if ((this._outstanding != value))
				{
					this.OnoutstandingChanging(value);
					this.SendPropertyChanging();
					this._outstanding = value;
					this.SendPropertyChanged("outstanding");
					this.OnoutstandingChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_loccode", DbType="VarChar(3) NOT NULL", CanBeNull=false)]
		public string loccode
		{
			get
			{
				return this._loccode;
			}
			set
			{
				if ((this._loccode != value))
				{
					this.OnloccodeChanging(value);
					this.SendPropertyChanging();
					this._loccode = value;
					this.SendPropertyChanged("loccode");
					this.OnloccodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_loccode2", DbType="VarChar(3) NOT NULL", CanBeNull=false)]
		public string loccode2
		{
			get
			{
				return this._loccode2;
			}
			set
			{
				if ((this._loccode2 != value))
				{
					this.Onloccode2Changing(value);
					this.SendPropertyChanging();
					this._loccode2 = value;
					this.SendPropertyChanged("loccode2");
					this.Onloccode2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_anuse", DbType="VarChar(9) NOT NULL", CanBeNull=false)]
		public string anuse
		{
			get
			{
				return this._anuse;
			}
			set
			{
				if ((this._anuse != value))
				{
					this.OnanuseChanging(value);
					this.SendPropertyChanging();
					this._anuse = value;
					this.SendPropertyChanged("anuse");
					this.OnanuseChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usethisperiod", DbType="Float NOT NULL")]
		public double usethisperiod
		{
			get
			{
				return this._usethisperiod;
			}
			set
			{
				if ((this._usethisperiod != value))
				{
					this.OnusethisperiodChanging(value);
					this.SendPropertyChanging();
					this._usethisperiod = value;
					this.SendPropertyChanged("usethisperiod");
					this.OnusethisperiodChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_recalcatperiodend", DbType="VarChar(1) NOT NULL")]
		public char recalcatperiodend
		{
			get
			{
				return this._recalcatperiodend;
			}
			set
			{
				if ((this._recalcatperiodend != value))
				{
					this.OnrecalcatperiodendChanging(value);
					this.SendPropertyChanging();
					this._recalcatperiodend = value;
					this.SendPropertyChanged("recalcatperiodend");
					this.OnrecalcatperiodendChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_datelastperiodend", DbType="VarChar(8)")]
		public string datelastperiodend
		{
			get
			{
				return this._datelastperiodend;
			}
			set
			{
				if ((this._datelastperiodend != value))
				{
					this.OndatelastperiodendChanging(value);
					this.SendPropertyChanging();
					this._datelastperiodend = value;
					this.SendPropertyChanged("datelastperiodend");
					this.OndatelastperiodendChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usagedamping", DbType="Float NOT NULL")]
		public double usagedamping
		{
			get
			{
				return this._usagedamping;
			}
			set
			{
				if ((this._usagedamping != value))
				{
					this.OnusagedampingChanging(value);
					this.SendPropertyChanging();
					this._usagedamping = value;
					this.SendPropertyChanged("usagedamping");
					this.OnusagedampingChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_safetyfactor", DbType="Float NOT NULL")]
		public double safetyfactor
		{
			get
			{
				return this._safetyfactor;
			}
			set
			{
				if ((this._safetyfactor != value))
				{
					this.OnsafetyfactorChanging(value);
					this.SendPropertyChanging();
					this._safetyfactor = value;
					this.SendPropertyChanged("safetyfactor");
					this.OnsafetyfactorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_supcode", DbType="VarChar(5)")]
		public string supcode
		{
			get
			{
				return this._supcode;
			}
			set
			{
				if ((this._supcode != value))
				{
					this.OnsupcodeChanging(value);
					this.SendPropertyChanging();
					this._supcode = value;
					this.SendPropertyChanged("supcode");
					this.OnsupcodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_altsupcode", DbType="VarChar(29)")]
		public string altsupcode
		{
			get
			{
				return this._altsupcode;
			}
			set
			{
				if ((this._altsupcode != value))
				{
					this.OnaltsupcodeChanging(value);
					this.SendPropertyChanging();
					this._altsupcode = value;
					this.SendPropertyChanged("altsupcode");
					this.OnaltsupcodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_contno", DbType="VarChar(10)")]
		public string contno
		{
			get
			{
				return this._contno;
			}
			set
			{
				if ((this._contno != value))
				{
					this.OncontnoChanging(value);
					this.SendPropertyChanging();
					this._contno = value;
					this.SendPropertyChanged("contno");
					this.OncontnoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lastordered", DbType="VarChar(8)")]
		public string lastordered
		{
			get
			{
				return this._lastordered;
			}
			set
			{
				if ((this._lastordered != value))
				{
					this.OnlastorderedChanging(value);
					this.SendPropertyChanging();
					this._lastordered = value;
					this.SendPropertyChanged("lastordered");
					this.OnlastorderedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_stocktakestatus", DbType="VarChar(1)")]
		public System.Nullable<char> stocktakestatus
		{
			get
			{
				return this._stocktakestatus;
			}
			set
			{
				if ((this._stocktakestatus != value))
				{
					this.OnstocktakestatusChanging(value);
					this.SendPropertyChanging();
					this._stocktakestatus = value;
					this.SendPropertyChanged("stocktakestatus");
					this.OnstocktakestatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_laststocktakedate", DbType="VarChar(8)")]
		public string laststocktakedate
		{
			get
			{
				return this._laststocktakedate;
			}
			set
			{
				if ((this._laststocktakedate != value))
				{
					this.OnlaststocktakedateChanging(value);
					this.SendPropertyChanging();
					this._laststocktakedate = value;
					this.SendPropertyChanged("laststocktakedate");
					this.OnlaststocktakedateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_laststocktaketime", DbType="VarChar(6)")]
		public string laststocktaketime
		{
			get
			{
				return this._laststocktaketime;
			}
			set
			{
				if ((this._laststocktaketime != value))
				{
					this.OnlaststocktaketimeChanging(value);
					this.SendPropertyChanging();
					this._laststocktaketime = value;
					this.SendPropertyChanged("laststocktaketime");
					this.OnlaststocktaketimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_batchtracking", DbType="VarChar(1) NOT NULL")]
		public char batchtracking
		{
			get
			{
				return this._batchtracking;
			}
			set
			{
				if ((this._batchtracking != value))
				{
					this.OnbatchtrackingChanging(value);
					this.SendPropertyChanging();
					this._batchtracking = value;
					this.SendPropertyChanged("batchtracking");
					this.OnbatchtrackingChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cost", DbType="VarChar(9) NOT NULL", CanBeNull=false)]
		public string cost
		{
			get
			{
				return this._cost;
			}
			set
			{
				if ((this._cost != value))
				{
					this.OncostChanging(value);
					this.SendPropertyChanging();
					this._cost = value;
					this.SendPropertyChanged("cost");
					this.OncostChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lossesgains", DbType="Float NOT NULL")]
		public double lossesgains
		{
			get
			{
				return this._lossesgains;
			}
			set
			{
				if ((this._lossesgains != value))
				{
					this.OnlossesgainsChanging(value);
					this.SendPropertyChanging();
					this._lossesgains = value;
					this.SendPropertyChanged("lossesgains");
					this.OnlossesgainsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ledcode", DbType="VarChar(7) NOT NULL", CanBeNull=false)]
		public string ledcode
		{
			get
			{
				return this._ledcode;
			}
			set
			{
				if ((this._ledcode != value))
				{
					this.OnledcodeChanging(value);
					this.SendPropertyChanging();
					this._ledcode = value;
					this.SendPropertyChanged("ledcode");
					this.OnledcodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pflag", DbType="VarChar(1) NOT NULL")]
		public char pflag
		{
			get
			{
				return this._pflag;
			}
			set
			{
				if ((this._pflag != value))
				{
					this.OnpflagChanging(value);
					this.SendPropertyChanging();
					this._pflag = value;
					this.SendPropertyChanged("pflag");
					this.OnpflagChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_message", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string message
		{
			get
			{
				return this._message;
			}
			set
			{
				if ((this._message != value))
				{
					this.OnmessageChanging(value);
					this.SendPropertyChanging();
					this._message = value;
					this.SendPropertyChanged("message");
					this.OnmessageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserMsg", DbType="VarChar(2) NOT NULL", CanBeNull=false)]
		public string UserMsg
		{
			get
			{
				return this._UserMsg;
			}
			set
			{
				if ((this._UserMsg != value))
				{
					this.OnUserMsgChanging(value);
					this.SendPropertyChanging();
					this._UserMsg = value;
					this.SendPropertyChanged("UserMsg");
					this.OnUserMsgChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PILnumber", DbType="Int NOT NULL")]
		public int PILnumber
		{
			get
			{
				return this._PILnumber;
			}
			set
			{
				if ((this._PILnumber != value))
				{
					this.OnPILnumberChanging(value);
					this.SendPropertyChanging();
					this._PILnumber = value;
					this.SendPropertyChanged("PILnumber");
					this.OnPILnumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PIL2", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string PIL2
		{
			get
			{
				return this._PIL2;
			}
			set
			{
				if ((this._PIL2 != value))
				{
					this.OnPIL2Changing(value);
					this.SendPropertyChanging();
					this._PIL2 = value;
					this.SendPropertyChanged("PIL2");
					this.OnPIL2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreatedUser", DbType="VarChar(3) NOT NULL", CanBeNull=false)]
		public string CreatedUser
		{
			get
			{
				return this._CreatedUser;
			}
			set
			{
				if ((this._CreatedUser != value))
				{
					this.OnCreatedUserChanging(value);
					this.SendPropertyChanging();
					this._CreatedUser = value;
					this.SendPropertyChanged("CreatedUser");
					this.OnCreatedUserChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_createdterminal", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string createdterminal
		{
			get
			{
				return this._createdterminal;
			}
			set
			{
				if ((this._createdterminal != value))
				{
					this.OncreatedterminalChanging(value);
					this.SendPropertyChanging();
					this._createdterminal = value;
					this.SendPropertyChanged("createdterminal");
					this.OncreatedterminalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_createddate", DbType="VarChar(8) NOT NULL", CanBeNull=false)]
		public string createddate
		{
			get
			{
				return this._createddate;
			}
			set
			{
				if ((this._createddate != value))
				{
					this.OncreateddateChanging(value);
					this.SendPropertyChanging();
					this._createddate = value;
					this.SendPropertyChanged("createddate");
					this.OncreateddateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_createdtime", DbType="VarChar(6) NOT NULL", CanBeNull=false)]
		public string createdtime
		{
			get
			{
				return this._createdtime;
			}
			set
			{
				if ((this._createdtime != value))
				{
					this.OncreatedtimeChanging(value);
					this.SendPropertyChanging();
					this._createdtime = value;
					this.SendPropertyChanged("createdtime");
					this.OncreatedtimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_modifieduser", DbType="VarChar(3) NOT NULL", CanBeNull=false)]
		public string modifieduser
		{
			get
			{
				return this._modifieduser;
			}
			set
			{
				if ((this._modifieduser != value))
				{
					this.OnmodifieduserChanging(value);
					this.SendPropertyChanging();
					this._modifieduser = value;
					this.SendPropertyChanged("modifieduser");
					this.OnmodifieduserChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_modifiedterminal", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string modifiedterminal
		{
			get
			{
				return this._modifiedterminal;
			}
			set
			{
				if ((this._modifiedterminal != value))
				{
					this.OnmodifiedterminalChanging(value);
					this.SendPropertyChanging();
					this._modifiedterminal = value;
					this.SendPropertyChanged("modifiedterminal");
					this.OnmodifiedterminalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_modifieddate", DbType="VarChar(8) NOT NULL", CanBeNull=false)]
		public string modifieddate
		{
			get
			{
				return this._modifieddate;
			}
			set
			{
				if ((this._modifieddate != value))
				{
					this.OnmodifieddateChanging(value);
					this.SendPropertyChanging();
					this._modifieddate = value;
					this.SendPropertyChanged("modifieddate");
					this.OnmodifieddateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_modifiedtime", DbType="VarChar(6) NOT NULL", CanBeNull=false)]
		public string modifiedtime
		{
			get
			{
				return this._modifiedtime;
			}
			set
			{
				if ((this._modifiedtime != value))
				{
					this.OnmodifiedtimeChanging(value);
					this.SendPropertyChanging();
					this._modifiedtime = value;
					this.SendPropertyChanged("modifiedtime");
					this.OnmodifiedtimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_local", DbType="VarChar(20)")]
		public string local
		{
			get
			{
				return this._local;
			}
			set
			{
				if ((this._local != value))
				{
					this.OnlocalChanging(value);
					this.SendPropertyChanging();
					this._local = value;
					this.SendPropertyChanged("local");
					this.OnlocalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ReconVol", DbType="Float")]
		public System.Nullable<double> ReconVol
		{
			get
			{
				return this._ReconVol;
			}
			set
			{
				if ((this._ReconVol != value))
				{
					this.OnReconVolChanging(value);
					this.SendPropertyChanging();
					this._ReconVol = value;
					this.SendPropertyChanged("ReconVol");
					this.OnReconVolChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ReconAbbr", DbType="VarChar(3)")]
		public string ReconAbbr
		{
			get
			{
				return this._ReconAbbr;
			}
			set
			{
				if ((this._ReconAbbr != value))
				{
					this.OnReconAbbrChanging(value);
					this.SendPropertyChanging();
					this._ReconAbbr = value;
					this.SendPropertyChanged("ReconAbbr");
					this.OnReconAbbrChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Diluent1", DbType="VarChar(3)")]
		public string Diluent1
		{
			get
			{
				return this._Diluent1;
			}
			set
			{
				if ((this._Diluent1 != value))
				{
					this.OnDiluent1Changing(value);
					this.SendPropertyChanging();
					this._Diluent1 = value;
					this.SendPropertyChanged("Diluent1");
					this.OnDiluent1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Diluent2", DbType="VarChar(3)")]
		public string Diluent2
		{
			get
			{
				return this._Diluent2;
			}
			set
			{
				if ((this._Diluent2 != value))
				{
					this.OnDiluent2Changing(value);
					this.SendPropertyChanging();
					this._Diluent2 = value;
					this.SendPropertyChanged("Diluent2");
					this.OnDiluent2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InfusionTime", DbType="Float")]
		public System.Nullable<double> InfusionTime
		{
			get
			{
				return this._InfusionTime;
			}
			set
			{
				if ((this._InfusionTime != value))
				{
					this.OnInfusionTimeChanging(value);
					this.SendPropertyChanging();
					this._InfusionTime = value;
					this.SendPropertyChanged("InfusionTime");
					this.OnInfusionTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Minmgperml", DbType="Float")]
		public System.Nullable<double> Minmgperml
		{
			get
			{
				return this._Minmgperml;
			}
			set
			{
				if ((this._Minmgperml != value))
				{
					this.OnMinmgpermlChanging(value);
					this.SendPropertyChanging();
					this._Minmgperml = value;
					this.SendPropertyChanged("Minmgperml");
					this.OnMinmgpermlChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Maxmgperml", DbType="Float")]
		public System.Nullable<double> Maxmgperml
		{
			get
			{
				return this._Maxmgperml;
			}
			set
			{
				if ((this._Maxmgperml != value))
				{
					this.OnMaxmgpermlChanging(value);
					this.SendPropertyChanging();
					this._Maxmgperml = value;
					this.SendPropertyChanged("Maxmgperml");
					this.OnMaxmgpermlChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IVContainer", DbType="VarChar(1)")]
		public System.Nullable<char> IVContainer
		{
			get
			{
				return this._IVContainer;
			}
			set
			{
				if ((this._IVContainer != value))
				{
					this.OnIVContainerChanging(value);
					this.SendPropertyChanging();
					this._IVContainer = value;
					this.SendPropertyChanged("IVContainer");
					this.OnIVContainerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DisplacementVolume", DbType="Float")]
		public System.Nullable<double> DisplacementVolume
		{
			get
			{
				return this._DisplacementVolume;
			}
			set
			{
				if ((this._DisplacementVolume != value))
				{
					this.OnDisplacementVolumeChanging(value);
					this.SendPropertyChanging();
					this._DisplacementVolume = value;
					this.SendPropertyChanged("DisplacementVolume");
					this.OnDisplacementVolumeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mgPerml", DbType="Float")]
		public System.Nullable<double> mgPerml
		{
			get
			{
				return this._mgPerml;
			}
			set
			{
				if ((this._mgPerml != value))
				{
					this.OnmgPermlChanging(value);
					this.SendPropertyChanging();
					this._mgPerml = value;
					this.SendPropertyChanged("mgPerml");
					this.OnmgPermlChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maxInfusionRate", DbType="Float")]
		public System.Nullable<double> maxInfusionRate
		{
			get
			{
				return this._maxInfusionRate;
			}
			set
			{
				if ((this._maxInfusionRate != value))
				{
					this.OnmaxInfusionRateChanging(value);
					this.SendPropertyChanging();
					this._maxInfusionRate = value;
					this.SendPropertyChanged("maxInfusionRate");
					this.OnmaxInfusionRateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CIVAS", DbType="VarChar(1)")]
		public System.Nullable<char> CIVAS
		{
			get
			{
				return this._CIVAS;
			}
			set
			{
				if ((this._CIVAS != value))
				{
					this.OnCIVASChanging(value);
					this.SendPropertyChanging();
					this._CIVAS = value;
					this.SendPropertyChanged("CIVAS");
					this.OnCIVASChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_convfact", DbType="Int")]
		public System.Nullable<int> convfact
		{
			get
			{
				return this._convfact;
			}
			set
			{
				if ((this._convfact != value))
				{
					this.OnconvfactChanging(value);
					this.SendPropertyChanging();
					this._convfact = value;
					this.SendPropertyChanged("convfact");
					this.OnconvfactChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DosesPerIssueUnit", DbType="Float")]
		public System.Nullable<double> DosesPerIssueUnit
		{
			get
			{
				return this._DosesPerIssueUnit;
			}
			set
			{
				if ((this._DosesPerIssueUnit != value))
				{
					this.OnDosesPerIssueUnitChanging(value);
					this.SendPropertyChanging();
					this._DosesPerIssueUnit = value;
					this.SendPropertyChanged("DosesPerIssueUnit");
					this.OnDosesPerIssueUnitChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StoresPack", DbType="VarChar(5)")]
		public string StoresPack
		{
			get
			{
				return this._StoresPack;
			}
			set
			{
				if ((this._StoresPack != value))
				{
					this.OnStoresPackChanging(value);
					this.SendPropertyChanging();
					this._StoresPack = value;
					this.SendPropertyChanged("StoresPack");
					this.OnStoresPackChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SessionLock", DbType="Int NOT NULL")]
		public int SessionLock
		{
			get
			{
				return this._SessionLock;
			}
			set
			{
				if ((this._SessionLock != value))
				{
					this.OnSessionLockChanging(value);
					this.SendPropertyChanging();
					this._SessionLock = value;
					this.SendPropertyChanged("SessionLock");
					this.OnSessionLockChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bnf", DbType="VarChar(13)")]
		public string bnf
		{
			get
			{
				return this._bnf;
			}
			set
			{
				if ((this._bnf != value))
				{
					this.OnbnfChanging(value);
					this.SendPropertyChanging();
					this._bnf = value;
					this.SendPropertyChanged("bnf");
					this.OnbnfChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Therapcode", DbType="VarChar(2)")]
		public string Therapcode
		{
			get
			{
				return this._Therapcode;
			}
			set
			{
				if ((this._Therapcode != value))
				{
					this.OnTherapcodeChanging(value);
					this.SendPropertyChanging();
					this._Therapcode = value;
					this.SendPropertyChanged("Therapcode");
					this.OnTherapcodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Reorderlvl", DbType="VarChar(8)")]
		public string Reorderlvl
		{
			get
			{
				return this._Reorderlvl;
			}
			set
			{
				if ((this._Reorderlvl != value))
				{
					this.OnReorderlvlChanging(value);
					this.SendPropertyChanging();
					this._Reorderlvl = value;
					this.SendPropertyChanged("Reorderlvl");
					this.OnReorderlvlChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ReorderQty", DbType="VarChar(6)")]
		public string ReorderQty
		{
			get
			{
				return this._ReorderQty;
			}
			set
			{
				if ((this._ReorderQty != value))
				{
					this.OnReorderQtyChanging(value);
					this.SendPropertyChanging();
					this._ReorderQty = value;
					this.SendPropertyChanged("ReorderQty");
					this.OnReorderQtyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DrugID", DbType="Int")]
		public System.Nullable<int> DrugID
		{
			get
			{
				return this._DrugID;
			}
			set
			{
				if ((this._DrugID != value))
				{
					this.OnDrugIDChanging(value);
					this.SendPropertyChanging();
					this._DrugID = value;
					this.SendPropertyChanged("DrugID");
					this.OnDrugIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Site_ProductStockInfo", Storage="_Site", ThisKey="LocationID_Site", OtherKey="LocationID", IsForeignKey=true)]
		public Site Site
		{
			get
			{
				return this._Site.Entity;
			}
			set
			{
				Site previousValue = this._Site.Entity;
				if (((previousValue != value) 
							|| (this._Site.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Site.Entity = null;
						previousValue.ProductStockInfos.Remove(this);
					}
					this._Site.Entity = value;
					if ((value != null))
					{
						value.ProductStockInfos.Add(this);
						this._LocationID_Site = value.LocationID;
					}
					else
					{
						this._LocationID_Site = default(int);
					}
					this.SendPropertyChanged("Site");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="sys.Site")]
	public partial class Site : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _LocationID;
		
		private int _SiteNumber;
		
		private EntitySet<ProductStockInfo> _ProductStocks;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnLocationIDChanging(int value);
    partial void OnLocationIDChanged();
    partial void OnSiteNumberChanging(int value);
    partial void OnSiteNumberChanged();
    #endregion
		
		public Site()
		{
			this._ProductStocks = new EntitySet<ProductStockInfo>(new Action<ProductStockInfo>(this.attach_ProductStocks), new Action<ProductStockInfo>(this.detach_ProductStocks));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LocationID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int LocationID
		{
			get
			{
				return this._LocationID;
			}
			set
			{
				if ((this._LocationID != value))
				{
					this.OnLocationIDChanging(value);
					this.SendPropertyChanging();
					this._LocationID = value;
					this.SendPropertyChanged("LocationID");
					this.OnLocationIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SiteNumber", DbType="Int NOT NULL")]
		public int SiteNumber
		{
			get
			{
				return this._SiteNumber;
			}
			set
			{
				if ((this._SiteNumber != value))
				{
					this.OnSiteNumberChanging(value);
					this.SendPropertyChanging();
					this._SiteNumber = value;
					this.SendPropertyChanged("SiteNumber");
					this.OnSiteNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Site_ProductStockInfo", Storage="_ProductStocks", ThisKey="LocationID", OtherKey="LocationID_Site")]
		public EntitySet<ProductStockInfo> ProductStockInfos
		{
			get
			{
				return this._ProductStocks;
			}
			set
			{
				this._ProductStocks.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ProductStocks(ProductStockInfo entity)
		{
			this.SendPropertyChanging();
			entity.Site = this;
		}
		
		private void detach_ProductStocks(ProductStockInfo entity)
		{
			this.SendPropertyChanging();
			entity.Site = null;
		}
	}
}
#pragma warning restore 1591
