<?xml version="1.0" encoding="utf-8"?>
<Database Name="PHARMACY_TESTING" Class="TestDBDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=devdb2-2005;Initial Catalog=PHARMACY_TESTING;User ID=icwsys" SettingsObjectName="Unit_Test_Business_Layer.Properties.Settings" SettingsPropertyName="PHARMACY_TESTINGConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="ProductStock" Member="ProductStockInfos">
    <Type Name="ProductStockInfo">
      <Column Name="ProductStockID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ProductID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="LocationID_Site" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="inuse" Type="System.Char" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="cyto" Type="System.Char" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="formulary" Type="System.Char" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="warcode" Type="System.String" DbType="VarChar(6)" CanBeNull="true" />
      <Column Name="warcode2" Type="System.String" DbType="VarChar(6)" CanBeNull="true" />
      <Column Name="inscode" Type="System.String" DbType="VarChar(6)" CanBeNull="true" />
      <Column Name="dircode" Type="System.String" DbType="VarChar(6)" CanBeNull="true" />
      <Column Name="labelformat" Type="System.Char" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="extralabel" Type="System.String" DbType="VarChar(3)" CanBeNull="true" />
      <Column Name="expiryminutes" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="minissue" Type="System.String" DbType="VarChar(4) NOT NULL" CanBeNull="false" />
      <Column Name="maxissue" Type="System.String" DbType="VarChar(5) NOT NULL" CanBeNull="false" />
      <Column Name="lastissued" Type="System.String" DbType="VarChar(8)" CanBeNull="true" />
      <Column Name="issueWholePack" Type="System.Char" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="stocklvl" Type="System.String" DbType="VarChar(9) NOT NULL" CanBeNull="false" />
      <Column Name="sisstock" Type="System.Char" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="livestockctrl" Type="System.Char" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="ordercycle" Type="System.String" DbType="VarChar(2)" CanBeNull="true" />
      <Column Name="cyclelength" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="outstanding" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="loccode" Type="System.String" DbType="VarChar(3) NOT NULL" CanBeNull="false" />
      <Column Name="loccode2" Type="System.String" DbType="VarChar(3) NOT NULL" CanBeNull="false" />
      <Column Name="anuse" Type="System.String" DbType="VarChar(9) NOT NULL" CanBeNull="false" />
      <Column Name="usethisperiod" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="recalcatperiodend" Type="System.Char" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="datelastperiodend" Type="System.String" DbType="VarChar(8)" CanBeNull="true" />
      <Column Name="usagedamping" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="safetyfactor" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="supcode" Type="System.String" DbType="VarChar(5)" CanBeNull="true" />
      <Column Name="altsupcode" Type="System.String" DbType="VarChar(29)" CanBeNull="true" />
      <Column Name="contno" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="lastordered" Type="System.String" DbType="VarChar(8)" CanBeNull="true" />
      <Column Name="stocktakestatus" Type="System.Char" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="laststocktakedate" Type="System.String" DbType="VarChar(8)" CanBeNull="true" />
      <Column Name="laststocktaketime" Type="System.String" DbType="VarChar(6)" CanBeNull="true" />
      <Column Name="batchtracking" Type="System.Char" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="cost" Type="System.String" DbType="VarChar(9) NOT NULL" CanBeNull="false" />
      <Column Name="lossesgains" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="ledcode" Type="System.String" DbType="VarChar(7) NOT NULL" CanBeNull="false" />
      <Column Name="pflag" Type="System.Char" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="message" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="UserMsg" Type="System.String" DbType="VarChar(2) NOT NULL" CanBeNull="false" />
      <Column Name="PILnumber" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PIL2" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="CreatedUser" Type="System.String" DbType="VarChar(3) NOT NULL" CanBeNull="false" />
      <Column Name="createdterminal" Type="System.String" DbType="VarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="createddate" Type="System.String" DbType="VarChar(8) NOT NULL" CanBeNull="false" />
      <Column Name="createdtime" Type="System.String" DbType="VarChar(6) NOT NULL" CanBeNull="false" />
      <Column Name="modifieduser" Type="System.String" DbType="VarChar(3) NOT NULL" CanBeNull="false" />
      <Column Name="modifiedterminal" Type="System.String" DbType="VarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="modifieddate" Type="System.String" DbType="VarChar(8) NOT NULL" CanBeNull="false" />
      <Column Name="modifiedtime" Type="System.String" DbType="VarChar(6) NOT NULL" CanBeNull="false" />
      <Column Name="local" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="ReconVol" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="ReconAbbr" Type="System.String" DbType="VarChar(3)" CanBeNull="true" />
      <Column Name="Diluent1" Type="System.String" DbType="VarChar(3)" CanBeNull="true" />
      <Column Name="Diluent2" Type="System.String" DbType="VarChar(3)" CanBeNull="true" />
      <Column Name="InfusionTime" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Minmgperml" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Maxmgperml" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="IVContainer" Type="System.Char" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="DisplacementVolume" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="mgPerml" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="maxInfusionRate" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="CIVAS" Type="System.Char" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="convfact" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DosesPerIssueUnit" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="StoresPack" Type="System.String" DbType="VarChar(5)" CanBeNull="true" />
      <Column Name="SessionLock" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="bnf" Type="System.String" DbType="VarChar(13)" CanBeNull="true" />
      <Column Name="Therapcode" Type="System.String" DbType="VarChar(2)" CanBeNull="true" />
      <Column Name="Reorderlvl" Type="System.String" DbType="VarChar(8)" CanBeNull="true" />
      <Column Name="ReorderQty" Type="System.String" DbType="VarChar(6)" CanBeNull="true" />
      <Column Name="DrugID" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="WRequis">
    <Type Name="WRequi">
      <Column Name="WRequisID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="RevisionLevel" Type="System.String" DbType="VarChar(2)" CanBeNull="true" />
      <Column Name="Code" Type="System.String" DbType="VarChar(7)" CanBeNull="true" />
      <Column Name="Outstanding" Type="System.String" DbType="VarChar(13)" CanBeNull="true" />
      <Column Name="OrdDate" Type="System.String" DbType="VarChar(8)" CanBeNull="true" />
      <Column Name="OrdTime" Type="System.String" DbType="VarChar(6)" CanBeNull="true" />
      <Column Name="LocCode" Type="System.String" DbType="VarChar(3)" CanBeNull="true" />
      <Column Name="SupCode" Type="System.String" DbType="VarChar(5)" CanBeNull="true" />
      <Column Name="Status" Type="System.Char" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="NumPrefix" Type="System.String" DbType="VarChar(6)" CanBeNull="true" />
      <Column Name="Num" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Cost" Type="System.String" DbType="VarChar(13)" CanBeNull="true" />
      <Column Name="PickNo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Received" Type="System.String" DbType="VarChar(13)" CanBeNull="true" />
      <Column Name="RecDate" Type="System.String" DbType="VarChar(8)" CanBeNull="true" />
      <Column Name="RecTime" Type="System.String" DbType="VarChar(6)" CanBeNull="true" />
      <Column Name="InvNum" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="PayDate" Type="System.String" DbType="VarChar(8)" CanBeNull="true" />
      <Column Name="QtyOrdered" Type="System.String" DbType="VarChar(13)" CanBeNull="true" />
      <Column Name="Urgency" Type="System.Char" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="ToFollow" Type="System.Char" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="InternalSiteNo" Type="System.String" DbType="VarChar(3)" CanBeNull="true" />
      <Column Name="InternalMethod" Type="System.Char" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="SupplierType" Type="System.Char" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="ConvFact" Type="System.String" DbType="VarChar(5)" CanBeNull="true" />
      <Column Name="IssueUnits" Type="System.String" DbType="VarChar(5)" CanBeNull="true" />
      <Column Name="Stocked" Type="System.Char" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="VarChar(56)" CanBeNull="true" />
      <Column Name="PFlag" Type="System.Char" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="CreatedUser" Type="System.String" DbType="VarChar(3)" CanBeNull="true" />
      <Column Name="CustOrdNo" Type="System.String" DbType="VarChar(12)" CanBeNull="true" />
      <Column Name="VATamount" Type="System.String" DbType="VarChar(13)" CanBeNull="true" />
      <Column Name="VatRateCode" Type="System.Char" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="VatRatePct" Type="System.String" DbType="VarChar(13)" CanBeNull="true" />
      <Column Name="VatInclusive" Type="System.String" DbType="VarChar(13)" CanBeNull="true" />
      <Column Name="InDispute" Type="System.Char" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="InDisputeUser" Type="System.String" DbType="VarChar(3)" CanBeNull="true" />
      <Column Name="ShelfPrinted" Type="System.Char" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="SiteID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="RequisitionNum" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="SessionLock" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="wProduct" Member="wProducts">
    <Type Name="wProduct">
      <Column Name="ProductID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="barcode" Type="System.String" DbType="VarChar(13)" CanBeNull="true" />
      <Column Name="siscode" Type="System.String" DbType="VarChar(7)" CanBeNull="true" />
      <Column Name="code" Type="System.String" DbType="VarChar(8)" CanBeNull="true" />
      <Column Name="labeldescription" Type="System.String" DbType="VarChar(56)" CanBeNull="true" />
      <Column Name="tradename" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="printformv" Type="System.String" DbType="VarChar(5)" CanBeNull="true" />
      <Column Name="storesdescription" Type="System.String" DbType="VarChar(56)" CanBeNull="true" />
      <Column Name="convfact" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="mlsperpack" Type="System.Single" DbType="Real" CanBeNull="true" />
      <Column Name="cyto" Type="System.Char" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="warcode" Type="System.String" DbType="VarChar(6)" CanBeNull="true" />
      <Column Name="warcode2" Type="System.String" DbType="VarChar(6)" CanBeNull="true" />
      <Column Name="inscode" Type="System.String" DbType="VarChar(6)" CanBeNull="true" />
      <Column Name="DosesperIssueUnit" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="DosingUnits" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="DPSForm" Type="System.String" DbType="VarChar(4)" CanBeNull="true" />
      <Column Name="Drugid" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="LabelInIssueUnits" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Canusespoon" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="DSSMasterSiteID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SiteProductDataID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="description" Type="System.String" DbType="VarChar(56)" CanBeNull="true" />
      <Column Name="bnf" Type="System.String" DbType="VarChar(13)" CanBeNull="true" />
      <Column Name="MinDailyDose" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="MaxDailyDose" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="MinDoseFrequency" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="MaxDoseFrequency" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="warcode_Locked" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="warcode2_Locked" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="inscode_Locked" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="StoresDescription_Locked" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="LabelDescription_Locked" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="ProductStockID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="LocationID_Site" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="inuse" Type="System.Char" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="formulary" Type="System.Char" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="labelformat" Type="System.Char" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="extralabel" Type="System.String" DbType="VarChar(3)" CanBeNull="true" />
      <Column Name="expiryminutes" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="minissue" Type="System.String" DbType="VarChar(4) NOT NULL" CanBeNull="false" />
      <Column Name="maxissue" Type="System.String" DbType="VarChar(5) NOT NULL" CanBeNull="false" />
      <Column Name="lastissued" Type="System.String" DbType="VarChar(8)" CanBeNull="true" />
      <Column Name="issueWholePack" Type="System.Char" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="stocklvl" Type="System.String" DbType="VarChar(9) NOT NULL" CanBeNull="false" />
      <Column Name="sisstock" Type="System.Char" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="livestockctrl" Type="System.Char" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="ordercycle" Type="System.String" DbType="VarChar(2)" CanBeNull="true" />
      <Column Name="cyclelength" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="outstanding" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="loccode" Type="System.String" DbType="VarChar(3) NOT NULL" CanBeNull="false" />
      <Column Name="loccode2" Type="System.String" DbType="VarChar(3) NOT NULL" CanBeNull="false" />
      <Column Name="anuse" Type="System.String" DbType="VarChar(9) NOT NULL" CanBeNull="false" />
      <Column Name="usethisperiod" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="recalcatperiodend" Type="System.Char" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="datelastperiodend" Type="System.String" DbType="VarChar(8)" CanBeNull="true" />
      <Column Name="usagedamping" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="safetyfactor" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="supcode" Type="System.String" DbType="VarChar(5)" CanBeNull="true" />
      <Column Name="altsupcode" Type="System.String" DbType="VarChar(29)" CanBeNull="true" />
      <Column Name="lastordered" Type="System.String" DbType="VarChar(8)" CanBeNull="true" />
      <Column Name="stocktakestatus" Type="System.Char" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="laststocktakedate" Type="System.String" DbType="VarChar(8)" CanBeNull="true" />
      <Column Name="laststocktaketime" Type="System.String" DbType="VarChar(6)" CanBeNull="true" />
      <Column Name="batchtracking" Type="System.Char" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="cost" Type="System.String" DbType="VarChar(9) NOT NULL" CanBeNull="false" />
      <Column Name="lossesgains" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="ledcode" Type="System.String" DbType="VarChar(7) NOT NULL" CanBeNull="false" />
      <Column Name="pflag" Type="System.Char" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="message" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="UserMsg" Type="System.String" DbType="VarChar(2) NOT NULL" CanBeNull="false" />
      <Column Name="PILnumber" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PIL2" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="CreatedUser" Type="System.String" DbType="VarChar(3) NOT NULL" CanBeNull="false" />
      <Column Name="createdterminal" Type="System.String" DbType="VarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="createddate" Type="System.String" DbType="VarChar(8) NOT NULL" CanBeNull="false" />
      <Column Name="createdtime" Type="System.String" DbType="VarChar(6) NOT NULL" CanBeNull="false" />
      <Column Name="modifieduser" Type="System.String" DbType="VarChar(3) NOT NULL" CanBeNull="false" />
      <Column Name="modifiedterminal" Type="System.String" DbType="VarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="modifieddate" Type="System.String" DbType="VarChar(8) NOT NULL" CanBeNull="false" />
      <Column Name="modifiedtime" Type="System.String" DbType="VarChar(6) NOT NULL" CanBeNull="false" />
      <Column Name="local" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="CIVAS" Type="System.Char" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="mgPerml" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="maxInfusionRate" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="InfusionTime" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Minmgperml" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Maxmgperml" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="IVContainer" Type="System.Char" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="DisplacementVolume" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="storespack" Type="System.String" DbType="VarChar(5)" CanBeNull="true" />
      <Column Name="therapcode" Type="System.String" DbType="VarChar(2)" CanBeNull="true" />
      <Column Name="reorderlvl" Type="System.String" DbType="VarChar(8)" CanBeNull="true" />
      <Column Name="reorderqty" Type="System.String" DbType="VarChar(6)" CanBeNull="true" />
      <Column Name="ReconVol" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="ReconAbbr" Type="System.String" DbType="VarChar(3)" CanBeNull="true" />
      <Column Name="Diluent1" Type="System.String" DbType="VarChar(3)" CanBeNull="true" />
      <Column Name="Diluent2" Type="System.String" DbType="VarChar(3)" CanBeNull="true" />
      <Column Name="SuppRefNo" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="WSupplierProfileID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="vatrate" Type="System.Char" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="sislistprice" Type="System.String" DbType="VarChar(9)" CanBeNull="true" />
      <Column Name="contprice" Type="System.String" DbType="VarChar(9)" CanBeNull="true" />
      <Column Name="lastreconcileprice" Type="System.String" DbType="VarChar(9)" CanBeNull="true" />
      <Column Name="contno" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="reorderpcksize" Type="System.String" DbType="VarChar(5)" CanBeNull="true" />
      <Column Name="leadtime" Type="System.String" DbType="VarChar(3)" CanBeNull="true" />
      <Column Name="SupplierTradeName" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="WSupplier" Member="WSuppliers">
    <Type Name="WSupplier">
      <Column Name="WSupplierID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Code" Type="System.String" DbType="VarChar(5) NOT NULL" CanBeNull="false" />
      <Column Name="ContractAddress" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="SupAddress" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="InvAddress" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="ContTelNo" Type="System.String" DbType="VarChar(14)" CanBeNull="true" />
      <Column Name="SupTelNo" Type="System.String" DbType="VarChar(14)" CanBeNull="true" />
      <Column Name="InvTelNo" Type="System.String" DbType="VarChar(14)" CanBeNull="true" />
      <Column Name="DiscountDesc" Type="System.String" DbType="VarChar(70)" CanBeNull="true" />
      <Column Name="DiscountVal" Type="System.String" DbType="VarChar(9)" CanBeNull="true" />
      <Column Name="Method" Type="System.Char" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="OrdMessage" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="AvLeadTime" Type="System.String" DbType="VarChar(4)" CanBeNull="true" />
      <Column Name="ContFaxNo" Type="System.String" DbType="VarChar(14)" CanBeNull="true" />
      <Column Name="SupFaxNo" Type="System.String" DbType="VarChar(14)" CanBeNull="true" />
      <Column Name="InvFaxNo" Type="System.String" DbType="VarChar(14)" CanBeNull="true" />
      <Column Name="Name" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="Ptn" Type="System.Char" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="PSis" Type="System.Char" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="FullName" Type="System.String" DbType="VarChar(35)" CanBeNull="true" />
      <Column Name="DiscountBelow" Type="System.String" DbType="VarChar(4)" CanBeNull="true" />
      <Column Name="DiscountAbove" Type="System.String" DbType="VarChar(4)" CanBeNull="true" />
      <Column Name="ICode" Type="System.String" DbType="VarChar(8)" CanBeNull="true" />
      <Column Name="CostCentre" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="PrintDeliveryNote" Type="System.Char" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="PrintPickTicket" Type="System.Char" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="SupplierType" Type="System.Char" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="OrderOutput" Type="System.Char" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="ReceiveGoods" Type="System.Char" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="TopupInterval" Type="System.String" DbType="VarChar(2)" CanBeNull="true" />
      <Column Name="AtcSupplied" Type="System.Char" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="TopupDate" Type="System.String" DbType="VarChar(8)" CanBeNull="true" />
      <Column Name="InUse" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="WardCode" Type="System.String" DbType="VarChar(5)" CanBeNull="true" />
      <Column Name="OnCost" Type="System.String" DbType="VarChar(3)" CanBeNull="true" />
      <Column Name="InPatientDirections" Type="System.Char" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="AdHocDelNote" Type="System.Char" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="SiteID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MinimumOrderValue" Type="System.Double" DbType="Float" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="Session" Member="Sessions">
    <Type Name="Session">
      <Column Name="SessionID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="EntityID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="LocationID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DateCreated" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="DateLastUsed" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Disconnected" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="icwsys.DSSMasterSiteLinkSite" Member="DSSMasterSiteLinkSites">
    <Type Name="DSSMasterSiteLinkSite">
      <Column Name="DSSMasterSiteLinkSiteID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="SiteID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DSSMasterSiteID" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Function Name="sys.spResetDBForSessionLockerTests" Method="spResetDBForSessionLockerTests">
    <Return Type="System.Int32" />
  </Function>
  <Function Name="sys.spResetDBForRequistionLineTests" Method="spResetDBForRequistionLineTests">
    <Return Type="System.Int32" />
  </Function>
  <Function Name="sys.spClearDB" Method="spClearDB">
    <Return Type="System.Int32" />
  </Function>
</Database>