//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HK_PMS.EIE {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="EIE.IIntegrationWebService")]
    public interface IIntegrationWebService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIntegrationWebService/Logon", ReplyAction="http://tempuri.org/IIntegrationWebService/LogonResponse")]
        string Logon(string UserName, string Password, string Location, bool OverrideSession);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIntegrationWebService/Logout", ReplyAction="http://tempuri.org/IIntegrationWebService/LogoutResponse")]
        string Logout(string Token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIntegrationWebService/Write", ReplyAction="http://tempuri.org/IIntegrationWebService/WriteResponse")]
        string Write(string Token, string SystemName, string EventName, string EventData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIntegrationWebService/Read", ReplyAction="http://tempuri.org/IIntegrationWebService/ReadResponse")]
        string Read(string Token, string SystemName, string EventName, string EventParameters);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IIntegrationWebServiceChannel : HK_PMS.EIE.IIntegrationWebService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class IntegrationWebServiceClient : System.ServiceModel.ClientBase<HK_PMS.EIE.IIntegrationWebService>, HK_PMS.EIE.IIntegrationWebService {
        
        public IntegrationWebServiceClient() {
        }
        
        public IntegrationWebServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public IntegrationWebServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IntegrationWebServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IntegrationWebServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string Logon(string UserName, string Password, string Location, bool OverrideSession) {
            return base.Channel.Logon(UserName, Password, Location, OverrideSession);
        }
        
        public string Logout(string Token) {
            return base.Channel.Logout(Token);
        }
        
        public string Write(string Token, string SystemName, string EventName, string EventData) {
            return base.Channel.Write(Token, SystemName, EventName, EventData);
        }
        
        public string Read(string Token, string SystemName, string EventName, string EventParameters) {
            return base.Channel.Read(Token, SystemName, EventName, EventParameters);
        }
    }
}
