//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client_Custom.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Client_Custom.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;
        ///	&lt;head&gt;
        ///		&lt;title&gt;[HTATITLE]&lt;/title&gt;
        ///		&lt;hta:application 
        ///			id=&quot;objHTA&quot; 
        ///			applicationname=&quot;EHSC&quot; 
        ///			icon=&quot;[HTTP]://[WEBSERVER]/[WEBSITE]/images/icons/ascribe.ico&quot;
        ///			innerborder=&quot;no&quot;
        ///			scroll=&quot;no&quot;
        ///			singleinstance=&quot;no&quot;
        ///			windowstate=&quot;maximize&quot;
        ///			navigable=&quot;yes&quot;
        ///			selection=&quot;no&quot; /&gt;
        ///	&lt;/head&gt;
        ///	&lt;frameset cols=&quot;1&quot; rows=&quot;1&quot;&gt;
        ///		&lt;frame 
        ///			src=&quot;[HTTP]://[WEBSERVER]/[WEBSITE]/hta.aspx&quot; 
        ///			application=&quot;yes&quot; 
        ///			frameborder=&quot;no&quot; 
        ///			tabindex=&quot;-1&quot; /&gt;
        ///	&lt;/frameset&gt;
        ///&lt;/html&gt;.
        /// </summary>
        internal static string htaTemplate {
            get {
                return ResourceManager.GetString("htaTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [InternetShortcut]
        ///URL=[HTTP]://[WEBSERVER]/[WEBSITE]/LauncherController.aspx
        ///IDList=
        ///IconFile=//[WEBSERVER]/[WEBSITE]/images/icons/ASCRIBE.ICO
        ///IconIndex=0
        ///HotKey=0
        ///[{000214A0-0000-0000-C000-000000000046}]
        ///Prop3=19,2.
        /// </summary>
        internal static string NonHTATemplate {
            get {
                return ResourceManager.GetString("NonHTATemplate", resourceCulture);
            }
        }
    }
}
