//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5466
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Data;



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName = "IWebDataService")]
public interface IWebDataService
{

    // CODEGEN: Parameter 'ExecuteSelectSPResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IWebDataService/ExecuteSelectSP", ReplyAction = "http://tempuri.org/IWebDataService/ExecuteSelectSPResponse")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    ExecuteSelectSPResponse ExecuteSelectSP(ExecuteSelectSPRequest request);

    // CODEGEN: Parameter 'ExecuteSelectOutputSPResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IWebDataService/ExecuteSelectOutputSP", ReplyAction = "http://tempuri.org/IWebDataService/ExecuteSelectOutputSPResponse")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    ExecuteSelectOutputSPResponse ExecuteSelectOutputSP(ExecuteSelectOutputSPRequest request);

    // CODEGEN: Parameter 'Procedure' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IWebDataService/ExecuteSelectReturnSP", ReplyAction = "http://tempuri.org/IWebDataService/ExecuteSelectReturnSPResponse")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    ExecuteSelectReturnSPResponse ExecuteSelectReturnSP(ExecuteSelectReturnSPRequest request);

    // CODEGEN: Parameter 'Procedure' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IWebDataService/ExecuteUpdateCustomSP", ReplyAction = "http://tempuri.org/IWebDataService/ExecuteUpdateCustomSPResponse")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    ExecuteUpdateCustomSPResponse ExecuteUpdateCustomSP(ExecuteUpdateCustomSPRequest request);

    // CODEGEN: Parameter 'TableName' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IWebDataService/ExecuteInsertSP", ReplyAction = "http://tempuri.org/IWebDataService/ExecuteInsertSPResponse")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    ExecuteInsertSPResponse ExecuteInsertSP(ExecuteInsertSPRequest request);

    // CODEGEN: Parameter 'TableName' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IWebDataService/ExecuteUpdateSP", ReplyAction = "http://tempuri.org/IWebDataService/ExecuteUpdateSPResponse")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    ExecuteUpdateSPResponse ExecuteUpdateSP(ExecuteUpdateSPRequest request);

    // CODEGEN: Parameter 'TableName' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IWebDataService/ExecuteDeleteSP", ReplyAction = "http://tempuri.org/IWebDataService/ExecuteDeleteSPResponse")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    ExecuteDeleteSPResponse ExecuteDeleteSP(ExecuteDeleteSPRequest request);

    // CODEGEN: Parameter 'TableName' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IWebDataService/ExecuteInsertLinkSP", ReplyAction = "http://tempuri.org/IWebDataService/ExecuteInsertLinkSPResponse")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    ExecuteInsertLinkSPResponse ExecuteInsertLinkSP(ExecuteInsertLinkSPRequest request);

    // CODEGEN: Parameter 'TableName' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IWebDataService/ExecuteDeleteLinkSP", ReplyAction = "http://tempuri.org/IWebDataService/ExecuteDeleteLinkSPResponse")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    ExecuteDeleteLinkSPResponse ExecuteDeleteLinkSP(ExecuteDeleteLinkSPRequest request);
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.MessageContractAttribute(WrapperName = "ExecuteSelectSP", WrapperNamespace = "http://tempuri.org/", IsWrapped = true)]
public partial class ExecuteSelectSPRequest
{

    [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://tempuri.org/", Order = 0)]
    public int SessionID;

    [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://tempuri.org/", Order = 1)]
    [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
    public string Procedure;

    [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://tempuri.org/", Order = 2)]
    [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
    public string ParametersXML;

    [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://tempuri.org/", Order = 3)]
    public bool FullSessionIDName;

    [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://tempuri.org/", Order = 4)]
    [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
    public string x;

    [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://tempuri.org/", Order = 5)]
    [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
    public string y;

    public ExecuteSelectSPRequest()
    {
    }

    public ExecuteSelectSPRequest(int SessionID, string Procedure, string ParametersXML, bool FullSessionIDName, string x, string y)
    {
        this.SessionID = SessionID;
        this.Procedure = Procedure;
        this.ParametersXML = ParametersXML;
        this.FullSessionIDName = FullSessionIDName;
        this.x = x;
        this.y = y;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.MessageContractAttribute(WrapperName = "ExecuteSelectSPResponse", WrapperNamespace = "http://tempuri.org/", IsWrapped = true)]
public partial class ExecuteSelectSPResponse
{

    [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://tempuri.org/", Order = 0)]
    [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
    public System.Data.DataSet ExecuteSelectSPResult;

    public ExecuteSelectSPResponse()
    {
    }

    public ExecuteSelectSPResponse(System.Data.DataSet ExecuteSelectSPResult)
    {
        this.ExecuteSelectSPResult = ExecuteSelectSPResult;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.MessageContractAttribute(WrapperName = "ExecuteSelectOutputSP", WrapperNamespace = "http://tempuri.org/", IsWrapped = true)]
public partial class ExecuteSelectOutputSPRequest
{

    [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://tempuri.org/", Order = 0)]
    public int SessionID;

    [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://tempuri.org/", Order = 1)]
    [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
    public string Procedure;

    [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://tempuri.org/", Order = 2)]
    [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
    public string ParametersXML;

    [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://tempuri.org/", Order = 3)]
    public bool FullSessionIDName;

    [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://tempuri.org/", Order = 4)]
    [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
    public string x;

    [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://tempuri.org/", Order = 5)]
    [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
    public string y;

    public ExecuteSelectOutputSPRequest()
    {
    }

    public ExecuteSelectOutputSPRequest(int SessionID, string Procedure, string ParametersXML, bool FullSessionIDName, string x, string y)
    {
        this.SessionID = SessionID;
        this.Procedure = Procedure;
        this.ParametersXML = ParametersXML;
        this.FullSessionIDName = FullSessionIDName;
        this.x = x;
        this.y = y;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.MessageContractAttribute(WrapperName = "ExecuteSelectOutputSPResponse", WrapperNamespace = "http://tempuri.org/", IsWrapped = true)]
public partial class ExecuteSelectOutputSPResponse
{

    [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://tempuri.org/", Order = 0)]
    [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
    public string ExecuteSelectOutputSPResult;

    public ExecuteSelectOutputSPResponse()
    {
    }

    public ExecuteSelectOutputSPResponse(string ExecuteSelectOutputSPResult)
    {
        this.ExecuteSelectOutputSPResult = ExecuteSelectOutputSPResult;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.MessageContractAttribute(WrapperName = "ExecuteSelectReturnSP", WrapperNamespace = "http://tempuri.org/", IsWrapped = true)]
public partial class ExecuteSelectReturnSPRequest
{

    [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://tempuri.org/", Order = 0)]
    public int SessionID;

    [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://tempuri.org/", Order = 1)]
    [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
    public string Procedure;

    [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://tempuri.org/", Order = 2)]
    [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
    public string ParametersXML;

    [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://tempuri.org/", Order = 3)]
    public bool FullSessionIDName;

    [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://tempuri.org/", Order = 4)]
    [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
    public string x;

    [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://tempuri.org/", Order = 5)]
    [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
    public string y;

    public ExecuteSelectReturnSPRequest()
    {
    }

    public ExecuteSelectReturnSPRequest(int SessionID, string Procedure, string ParametersXML, bool FullSessionIDName, string x, string y)
    {
        this.SessionID = SessionID;
        this.Procedure = Procedure;
        this.ParametersXML = ParametersXML;
        this.FullSessionIDName = FullSessionIDName;
        this.x = x;
        this.y = y;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.MessageContractAttribute(WrapperName = "ExecuteSelectReturnSPResponse", WrapperNamespace = "http://tempuri.org/", IsWrapped = true)]
public partial class ExecuteSelectReturnSPResponse
{

    [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://tempuri.org/", Order = 0)]
    public int ExecuteSelectReturnSPResult;

    public ExecuteSelectReturnSPResponse()
    {
    }

    public ExecuteSelectReturnSPResponse(int ExecuteSelectReturnSPResult)
    {
        this.ExecuteSelectReturnSPResult = ExecuteSelectReturnSPResult;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.MessageContractAttribute(WrapperName = "ExecuteUpdateCustomSP", WrapperNamespace = "http://tempuri.org/", IsWrapped = true)]
public partial class ExecuteUpdateCustomSPRequest
{

    [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://tempuri.org/", Order = 0)]
    public int SessionID;

    [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://tempuri.org/", Order = 1)]
    [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
    public string Procedure;

    [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://tempuri.org/", Order = 2)]
    [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
    public string ParametersXML;

    [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://tempuri.org/", Order = 3)]
    public bool FullSessionIDName;

    [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://tempuri.org/", Order = 4)]
    [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
    public string x;

    [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://tempuri.org/", Order = 5)]
    [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
    public string y;

    public ExecuteUpdateCustomSPRequest()
    {
    }

    public ExecuteUpdateCustomSPRequest(int SessionID, string Procedure, string ParametersXML, bool FullSessionIDName, string x, string y)
    {
        this.SessionID = SessionID;
        this.Procedure = Procedure;
        this.ParametersXML = ParametersXML;
        this.FullSessionIDName = FullSessionIDName;
        this.x = x;
        this.y = y;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.MessageContractAttribute(WrapperName = "ExecuteUpdateCustomSPResponse", WrapperNamespace = "http://tempuri.org/", IsWrapped = true)]
public partial class ExecuteUpdateCustomSPResponse
{

    [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://tempuri.org/", Order = 0)]
    public int ExecuteUpdateCustomSPResult;

    public ExecuteUpdateCustomSPResponse()
    {
    }

    public ExecuteUpdateCustomSPResponse(int ExecuteUpdateCustomSPResult)
    {
        this.ExecuteUpdateCustomSPResult = ExecuteUpdateCustomSPResult;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.MessageContractAttribute(WrapperName = "ExecuteInsertSP", WrapperNamespace = "http://tempuri.org/", IsWrapped = true)]
public partial class ExecuteInsertSPRequest
{

    [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://tempuri.org/", Order = 0)]
    public int SessionID;

    [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://tempuri.org/", Order = 1)]
    [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
    public string TableName;

    [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://tempuri.org/", Order = 2)]
    [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
    public string ParametersXML;

    [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://tempuri.org/", Order = 3)]
    public bool FullSessionIDName;

    [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://tempuri.org/", Order = 4)]
    [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
    public string x;

    [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://tempuri.org/", Order = 5)]
    [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
    public string y;

    public ExecuteInsertSPRequest()
    {
    }

    public ExecuteInsertSPRequest(int SessionID, string TableName, string ParametersXML, bool FullSessionIDName, string x, string y)
    {
        this.SessionID = SessionID;
        this.TableName = TableName;
        this.ParametersXML = ParametersXML;
        this.FullSessionIDName = FullSessionIDName;
        this.x = x;
        this.y = y;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.MessageContractAttribute(WrapperName = "ExecuteInsertSPResponse", WrapperNamespace = "http://tempuri.org/", IsWrapped = true)]
public partial class ExecuteInsertSPResponse
{

    [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://tempuri.org/", Order = 0)]
    public int ExecuteInsertSPResult;

    public ExecuteInsertSPResponse()
    {
    }

    public ExecuteInsertSPResponse(int ExecuteInsertSPResult)
    {
        this.ExecuteInsertSPResult = ExecuteInsertSPResult;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.MessageContractAttribute(WrapperName = "ExecuteUpdateSP", WrapperNamespace = "http://tempuri.org/", IsWrapped = true)]
public partial class ExecuteUpdateSPRequest
{

    [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://tempuri.org/", Order = 0)]
    public int SessionID;

    [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://tempuri.org/", Order = 1)]
    [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
    public string TableName;

    [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://tempuri.org/", Order = 2)]
    [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
    public string ParametersXML;

    [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://tempuri.org/", Order = 3)]
    public bool FullSessionIDName;

    [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://tempuri.org/", Order = 4)]
    [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
    public string x;

    [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://tempuri.org/", Order = 5)]
    [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
    public string y;

    public ExecuteUpdateSPRequest()
    {
    }

    public ExecuteUpdateSPRequest(int SessionID, string TableName, string ParametersXML, bool FullSessionIDName, string x, string y)
    {
        this.SessionID = SessionID;
        this.TableName = TableName;
        this.ParametersXML = ParametersXML;
        this.FullSessionIDName = FullSessionIDName;
        this.x = x;
        this.y = y;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.MessageContractAttribute(WrapperName = "ExecuteUpdateSPResponse", WrapperNamespace = "http://tempuri.org/", IsWrapped = true)]
public partial class ExecuteUpdateSPResponse
{

    [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://tempuri.org/", Order = 0)]
    public int ExecuteUpdateSPResult;

    public ExecuteUpdateSPResponse()
    {
    }

    public ExecuteUpdateSPResponse(int ExecuteUpdateSPResult)
    {
        this.ExecuteUpdateSPResult = ExecuteUpdateSPResult;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.MessageContractAttribute(WrapperName = "ExecuteDeleteSP", WrapperNamespace = "http://tempuri.org/", IsWrapped = true)]
public partial class ExecuteDeleteSPRequest
{

    [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://tempuri.org/", Order = 0)]
    public int SessionID;

    [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://tempuri.org/", Order = 1)]
    [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
    public string TableName;

    [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://tempuri.org/", Order = 2)]
    public int PrimaryKey;

    [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://tempuri.org/", Order = 3)]
    public bool FullSessionIDName;

    [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://tempuri.org/", Order = 4)]
    [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
    public string x;

    [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://tempuri.org/", Order = 5)]
    [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
    public string y;

    public ExecuteDeleteSPRequest()
    {
    }

    public ExecuteDeleteSPRequest(int SessionID, string TableName, int PrimaryKey, bool FullSessionIDName, string x, string y)
    {
        this.SessionID = SessionID;
        this.TableName = TableName;
        this.PrimaryKey = PrimaryKey;
        this.FullSessionIDName = FullSessionIDName;
        this.x = x;
        this.y = y;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.MessageContractAttribute(WrapperName = "ExecuteDeleteSPResponse", WrapperNamespace = "http://tempuri.org/", IsWrapped = true)]
public partial class ExecuteDeleteSPResponse
{

    [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://tempuri.org/", Order = 0)]
    public int ExecuteDeleteSPResult;

    public ExecuteDeleteSPResponse()
    {
    }

    public ExecuteDeleteSPResponse(int ExecuteDeleteSPResult)
    {
        this.ExecuteDeleteSPResult = ExecuteDeleteSPResult;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.MessageContractAttribute(WrapperName = "ExecuteInsertLinkSP", WrapperNamespace = "http://tempuri.org/", IsWrapped = true)]
public partial class ExecuteInsertLinkSPRequest
{

    [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://tempuri.org/", Order = 0)]
    public int SessionID;

    [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://tempuri.org/", Order = 1)]
    [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
    public string TableName;

    [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://tempuri.org/", Order = 2)]
    [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
    public string ParametersXML;

    [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://tempuri.org/", Order = 3)]
    public bool FullSessionIDName;

    [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://tempuri.org/", Order = 4)]
    [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
    public string x;

    [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://tempuri.org/", Order = 5)]
    [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
    public string y;

    public ExecuteInsertLinkSPRequest()
    {
    }

    public ExecuteInsertLinkSPRequest(int SessionID, string TableName, string ParametersXML, bool FullSessionIDName, string x, string y)
    {
        this.SessionID = SessionID;
        this.TableName = TableName;
        this.ParametersXML = ParametersXML;
        this.FullSessionIDName = FullSessionIDName;
        this.x = x;
        this.y = y;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.MessageContractAttribute(WrapperName = "ExecuteInsertLinkSPResponse", WrapperNamespace = "http://tempuri.org/", IsWrapped = true)]
public partial class ExecuteInsertLinkSPResponse
{

    [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://tempuri.org/", Order = 0)]
    public int ExecuteInsertLinkSPResult;

    public ExecuteInsertLinkSPResponse()
    {
    }

    public ExecuteInsertLinkSPResponse(int ExecuteInsertLinkSPResult)
    {
        this.ExecuteInsertLinkSPResult = ExecuteInsertLinkSPResult;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.MessageContractAttribute(WrapperName = "ExecuteDeleteLinkSP", WrapperNamespace = "http://tempuri.org/", IsWrapped = true)]
public partial class ExecuteDeleteLinkSPRequest
{

    [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://tempuri.org/", Order = 0)]
    public int SessionID;

    [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://tempuri.org/", Order = 1)]
    [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
    public string TableName;

    [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://tempuri.org/", Order = 2)]
    [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
    public string ParametersXML;

    [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://tempuri.org/", Order = 3)]
    public bool FullSessionIDName;

    [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://tempuri.org/", Order = 4)]
    [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
    public string x;

    [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://tempuri.org/", Order = 5)]
    [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
    public string y;

    public ExecuteDeleteLinkSPRequest()
    {
    }

    public ExecuteDeleteLinkSPRequest(int SessionID, string TableName, string ParametersXML, bool FullSessionIDName, string x, string y)
    {
        this.SessionID = SessionID;
        this.TableName = TableName;
        this.ParametersXML = ParametersXML;
        this.FullSessionIDName = FullSessionIDName;
        this.x = x;
        this.y = y;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.MessageContractAttribute(WrapperName = "ExecuteDeleteLinkSPResponse", WrapperNamespace = "http://tempuri.org/", IsWrapped = true)]
public partial class ExecuteDeleteLinkSPResponse
{

    [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://tempuri.org/", Order = 0)]
    public int ExecuteDeleteLinkSPResult;

    public ExecuteDeleteLinkSPResponse()
    {
    }

    public ExecuteDeleteLinkSPResponse(int ExecuteDeleteLinkSPResult)
    {
        this.ExecuteDeleteLinkSPResult = ExecuteDeleteLinkSPResult;
    }
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public interface IWebDataServiceChannel : IWebDataService, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public partial class WebDataServiceClient : System.ServiceModel.ClientBase<IWebDataService>, IWebDataService
{

    public WebDataServiceClient()
    {
    }

    public WebDataServiceClient(string endpointConfigurationName) :
        base(endpointConfigurationName)
    {
    }

    public WebDataServiceClient(string endpointConfigurationName, string remoteAddress) :
        base(endpointConfigurationName, remoteAddress)
    {
    }

    public WebDataServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) :
        base(endpointConfigurationName, remoteAddress)
    {
    }

    public WebDataServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
        base(binding, remoteAddress)
    {
    }

    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    ExecuteSelectSPResponse IWebDataService.ExecuteSelectSP(ExecuteSelectSPRequest request)
    {
        return base.Channel.ExecuteSelectSP(request);
    }

    public System.Data.DataSet ExecuteSelectSP(int SessionID, string Procedure, string ParametersXML, bool FullSessionIDName, string x, string y)
    {
        ExecuteSelectSPRequest inValue = new ExecuteSelectSPRequest();
        inValue.SessionID = SessionID;
        inValue.Procedure = Procedure;
        inValue.ParametersXML = ParametersXML;
        inValue.FullSessionIDName = FullSessionIDName;
        inValue.x = x;
        inValue.y = y;
        ExecuteSelectSPResponse retVal = ((IWebDataService)(this)).ExecuteSelectSP(inValue);
        return retVal.ExecuteSelectSPResult;
    }

    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    ExecuteSelectOutputSPResponse IWebDataService.ExecuteSelectOutputSP(ExecuteSelectOutputSPRequest request)
    {
        return base.Channel.ExecuteSelectOutputSP(request);
    }

    public string ExecuteSelectOutputSP(int SessionID, string Procedure, string ParametersXML, bool FullSessionIDName, string x, string y)
    {
        ExecuteSelectOutputSPRequest inValue = new ExecuteSelectOutputSPRequest();
        inValue.SessionID = SessionID;
        inValue.Procedure = Procedure;
        inValue.ParametersXML = ParametersXML;
        inValue.FullSessionIDName = FullSessionIDName;
        inValue.x = x;
        inValue.y = y;
        ExecuteSelectOutputSPResponse retVal = ((IWebDataService)(this)).ExecuteSelectOutputSP(inValue);
        return retVal.ExecuteSelectOutputSPResult;
    }

    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    ExecuteSelectReturnSPResponse IWebDataService.ExecuteSelectReturnSP(ExecuteSelectReturnSPRequest request)
    {
        return base.Channel.ExecuteSelectReturnSP(request);
    }

    public int ExecuteSelectReturnSP(int SessionID, string Procedure, string ParametersXML, bool FullSessionIDName, string x, string y)
    {
        ExecuteSelectReturnSPRequest inValue = new ExecuteSelectReturnSPRequest();
        inValue.SessionID = SessionID;
        inValue.Procedure = Procedure;
        inValue.ParametersXML = ParametersXML;
        inValue.FullSessionIDName = FullSessionIDName;
        inValue.x = x;
        inValue.y = y;
        ExecuteSelectReturnSPResponse retVal = ((IWebDataService)(this)).ExecuteSelectReturnSP(inValue);
        return retVal.ExecuteSelectReturnSPResult;
    }

    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    ExecuteUpdateCustomSPResponse IWebDataService.ExecuteUpdateCustomSP(ExecuteUpdateCustomSPRequest request)
    {
        return base.Channel.ExecuteUpdateCustomSP(request);
    }

    public int ExecuteUpdateCustomSP(int SessionID, string Procedure, string ParametersXML, bool FullSessionIDName, string x, string y)
    {
        ExecuteUpdateCustomSPRequest inValue = new ExecuteUpdateCustomSPRequest();
        inValue.SessionID = SessionID;
        inValue.Procedure = Procedure;
        inValue.ParametersXML = ParametersXML;
        inValue.FullSessionIDName = FullSessionIDName;
        inValue.x = x;
        inValue.y = y;
        ExecuteUpdateCustomSPResponse retVal = ((IWebDataService)(this)).ExecuteUpdateCustomSP(inValue);
        return retVal.ExecuteUpdateCustomSPResult;
    }

    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    ExecuteInsertSPResponse IWebDataService.ExecuteInsertSP(ExecuteInsertSPRequest request)
    {
        return base.Channel.ExecuteInsertSP(request);
    }

    public int ExecuteInsertSP(int SessionID, string TableName, string ParametersXML, bool FullSessionIDName, string x, string y)
    {
        ExecuteInsertSPRequest inValue = new ExecuteInsertSPRequest();
        inValue.SessionID = SessionID;
        inValue.TableName = TableName;
        inValue.ParametersXML = ParametersXML;
        inValue.FullSessionIDName = FullSessionIDName;
        inValue.x = x;
        inValue.y = y;
        ExecuteInsertSPResponse retVal = ((IWebDataService)(this)).ExecuteInsertSP(inValue);
        return retVal.ExecuteInsertSPResult;
    }

    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    ExecuteUpdateSPResponse IWebDataService.ExecuteUpdateSP(ExecuteUpdateSPRequest request)
    {
        return base.Channel.ExecuteUpdateSP(request);
    }

    public int ExecuteUpdateSP(int SessionID, string TableName, string ParametersXML, bool FullSessionIDName, string x, string y)
    {
        ExecuteUpdateSPRequest inValue = new ExecuteUpdateSPRequest();
        inValue.SessionID = SessionID;
        inValue.TableName = TableName;
        inValue.ParametersXML = ParametersXML;
        inValue.FullSessionIDName = FullSessionIDName;
        inValue.x = x;
        inValue.y = y;
        ExecuteUpdateSPResponse retVal = ((IWebDataService)(this)).ExecuteUpdateSP(inValue);
        return retVal.ExecuteUpdateSPResult;
    }

    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    ExecuteDeleteSPResponse IWebDataService.ExecuteDeleteSP(ExecuteDeleteSPRequest request)
    {
        return base.Channel.ExecuteDeleteSP(request);
    }

    public int ExecuteDeleteSP(int SessionID, string TableName, int PrimaryKey, bool FullSessionIDName, string x, string y)
    {
        ExecuteDeleteSPRequest inValue = new ExecuteDeleteSPRequest();
        inValue.SessionID = SessionID;
        inValue.TableName = TableName;
        inValue.PrimaryKey = PrimaryKey;
        inValue.FullSessionIDName = FullSessionIDName;
        inValue.x = x;
        inValue.y = y;
        ExecuteDeleteSPResponse retVal = ((IWebDataService)(this)).ExecuteDeleteSP(inValue);
        return retVal.ExecuteDeleteSPResult;
    }

    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    ExecuteInsertLinkSPResponse IWebDataService.ExecuteInsertLinkSP(ExecuteInsertLinkSPRequest request)
    {
        return base.Channel.ExecuteInsertLinkSP(request);
    }

    public int ExecuteInsertLinkSP(int SessionID, string TableName, string ParametersXML, bool FullSessionIDName, string x, string y)
    {
        ExecuteInsertLinkSPRequest inValue = new ExecuteInsertLinkSPRequest();
        inValue.SessionID = SessionID;
        inValue.TableName = TableName;
        inValue.ParametersXML = ParametersXML;
        inValue.FullSessionIDName = FullSessionIDName;
        inValue.x = x;
        inValue.y = y;
        ExecuteInsertLinkSPResponse retVal = ((IWebDataService)(this)).ExecuteInsertLinkSP(inValue);
        return retVal.ExecuteInsertLinkSPResult;
    }

    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    ExecuteDeleteLinkSPResponse IWebDataService.ExecuteDeleteLinkSP(ExecuteDeleteLinkSPRequest request)
    {
        return base.Channel.ExecuteDeleteLinkSP(request);
    }

    public int ExecuteDeleteLinkSP(int SessionID, string TableName, string ParametersXML, bool FullSessionIDName, string x, string y)
    {
        ExecuteDeleteLinkSPRequest inValue = new ExecuteDeleteLinkSPRequest();
        inValue.SessionID = SessionID;
        inValue.TableName = TableName;
        inValue.ParametersXML = ParametersXML;
        inValue.FullSessionIDName = FullSessionIDName;
        inValue.x = x;
        inValue.y = y;
        ExecuteDeleteLinkSPResponse retVal = ((IWebDataService)(this)).ExecuteDeleteLinkSP(inValue);
        return retVal.ExecuteDeleteLinkSPResult;
    }
}
