IF OBJECT_ID('tempDB..#rDatabase') IS NOT NULL
	DROP TABLE #rDatabase

IF OBJECT_ID('rDatabase') IS NOT NULL
	BEGIN
		SELECT * INTO #rDatabase FROM rDatabase
		DROP TABLE rDatabase
	END
GO

CREATE TABLE rDatabase (
	DATABASE_TYPE varchar (10) PRIMARY KEY NOT NULL ,
	DATABASE_NAME varchar (215) NULL ,
	DATABASE_VERSION varchar (25) NULL
) 
GO

INSERT INTO rDatabase (
	DATABASE_TYPE
,	DATABASE_NAME
)
(
SELECT 
	'LIVE'		DATABASE_TYPE
,	'ASC_LIVE' 	DATABASE_NAME
UNION
SELECT
	'REPORTING'		DATABASE_TYPE
,	'ASC_REPORT' 	DATABASE_NAME
)

IF OBJECT_ID('tempDB..#rDatabase') IS NULL
	RETURN

UPDATE rDatabase 
SET DATABASE_NAME = B.DATABASE_NAME
FROM rDatabase A INNER JOIN #rDatabase B ON A.DATABASE_TYPE = B.DATABASE_TYPE

select * from rDatabase
