IF OBJECT_ID('rFormula') IS NOT NULL
	DROP TABLE rFormula
GO

CREATE TABLE rFormula (
	[WFormulaID] [int] NOT NULL ,
	[LocationID_Site] [int] NOT NULL ,
	[Authorised2] [varchar] (5)  NULL ,
	[Layout2] [varchar] (50) NULL ,
	[NSVcode] [varchar] (7) NULL ,
	[code1] [varchar] (7) NULL ,
	[code2] [varchar] (7) NULL ,
	[code3] [varchar] (7) NULL ,
	[code4] [varchar] (7) NULL ,
	[code5] [varchar] (7) NULL ,
	[code6] [varchar] (7) NULL ,
	[code7] [varchar] (7) NULL ,
	[code8] [varchar] (7) NULL ,
	[code9] [varchar] (7) NULL ,
	[code10] [varchar] (7) NULL ,
	[code11] [varchar] (7) NULL ,
	[code12] [varchar] (7) NULL ,
	[code13] [varchar] (7) NULL ,
	[code14] [varchar] (7) NULL ,
	[code15] [varchar] (7) NULL ,
	[qty1] [float] NULL ,
	[qty2] [float] NULL ,
	[qty3] [float] NULL ,
	[qty4] [float] NULL ,
	[qty5] [float] NULL ,
	[qty6] [float] NULL ,
	[qty7] [float] NULL ,
	[qty8] [float] NULL ,
	[qty9] [float] NULL ,
	[qty10] [float] NULL ,
	[qty11] [float] NULL ,
	[qty12] [float] NULL ,
	[qty13] [float] NULL ,
	[qty14] [float] NULL ,
	[qty15] [float] NULL ,
	[type1] [varchar] (1) NULL ,
	[type2] [varchar] (1) NULL ,
	[type3] [varchar] (1) NULL ,
	[type4] [varchar] (1) NULL ,
	[type5] [varchar] (1) NULL ,
	[type6] [varchar] (1) NULL ,
	[type7] [varchar] (1) NULL ,
	[type8] [varchar] (1) NULL ,
	[type9] [varchar] (1) NULL ,
	[type10] [varchar] (1) NULL ,
	[type11] [varchar] (1) NULL ,
	[type12] [varchar] (1) NULL ,
	[type13] [varchar] (1) NULL ,
	[type14] [varchar] (1) NULL ,
	[type15] [varchar] (1) NULL ,
	[Method] [varchar] (1024) NULL ,
	[TotalQty] [float] NULL ,
	[NumofLabels] [int] NULL ,
	[Label] [varchar] (MAX) NULL ,
	[ExtraLabels] [int] NULL ,
	[DosingUnits] [bit] NULL ,
	[d1] [varchar] (60) NULL ,
	[d2] [varchar] (60) NULL ,
	[d3] [varchar] (60) NULL ,
	[d4] [varchar] (60) NULL ,
	[d5] [varchar] (60) NULL ,
	[d6] [varchar] (60) NULL ,
	[d7] [varchar] (60) NULL ,
	[d8] [varchar] (60) NULL ,
	[d9] [varchar] (60) NULL ,
	[d10] [varchar] (60) NULL ,
	[d11] [varchar] (60) NULL ,
	[d12] [varchar] (60) NULL ,
	[d13] [varchar] (60) NULL ,
	[d14] [varchar] (60) NULL ,
	[d15] [varchar] (60) NULL ,
	[Authorised] [varchar] (5) NULL ,
	[Authorised_Date] [datetime] NULL ,
	[Layout] [varchar] (10) NULL ,
	[WManufacturingStatusID] [int] NULL ,
	[EntityID_Drafted] [int] NULL,
	[EntityID_Approved] [int] NULL,
	[DateDrafted] [datetime] NULL,
	[DateApproved] [datetime] NULL ,
	[VersionNumber] [int] NULL 
	
) 
GO


