@echo off

osql -S %1 -U %2 -P %3 -d %4 -n -i "v8 Converted Patient Notes insert sp.sql"
osql -S %1 -U %2 -P %3 -d %4 -n -i "V8 Create Alias Group sp.sql"
osql -S %1 -U %2 -P %3 -d %4 -n -i "v8 Batch Stock Level Insert sp.sql"
osql -S %1 -U %2 -P %3 -d %4 -n -i "V8 Create EntityRole Entry sp.sql"
osql -S %1 -U %2 -P %3 -d %4 -n -i "V8 Create Gender Entry sp.sql"
osql -S %1 -U %2 -P %3 -d %4 -n -i "V8 Conversion Metadata sp.sql"
osql -S %1 -U %2 -P %3 -d %4 -n -i "V8 Consultant Insert sp.sql"
osql -S %1 -U %2 -P %3 -d %4 -n -i "V8 Conv WLabel Insert.sql"
osql -S %1 -U %2 -P %3 -d %4 -n -i "V8 conversion site insert sp.sql"
osql -S %1 -U %2 -P %3 -d %4 -n -i "V8 direction insert sp.sql"
osql -S %1 -U %2 -P %3 -d %4 -n -i "V8 Episode Insert sp.sql"
osql -S %1 -U %2 -P %3 -d %4 -n -i "V8 Extra Supplier Data Insert sp.sql"
osql -S %1 -U %2 -P %3 -d %4 -n -i "V8 GP Insert sp.sql"
osql -S %1 -U %2 -P %3 -d %4 -n -i "V8 Label Insert sp.sql"
osql -S %1 -U %2 -P %3 -d %4 -n -i "V8 Lookup Context Insert sp.sql"
osql -S %1 -U %2 -P %3 -d %4 -n -i "V8 order insert sp.sql"
osql -S %1 -U %2 -P %3 -d %4 -n -i "V8 Patient Conversion Insert sp.sql"
osql -S %1 -U %2 -P %3 -d %4 -n -i "V8 Patient Conversion Table Create.sql"
osql -S %1 -U %2 -P %3 -d %4 -n -i "V8 Patient Insert sp.sql"
osql -S %1 -U %2 -P %3 -d %4 -n -i "V8 Read Pointer Insert sp.sql"
osql -S %1 -U %2 -P %3 -d %4 -n -i "V8 reconciliation insert sp.sql"
osql -S %1 -U %2 -P %3 -d %4 -n -i "v8 requisition insert sp.sql"
osql -S %1 -U %2 -P %3 -d %4 -n -i "v8 rx log insert sp.sql"
osql -S %1 -U %2 -P %3 -d %4 -n -i "v8 site insert sp.sql"
osql -S %1 -U %2 -P %3 -d %4 -n -i "v8 specialty insert sp.sql"
osql -S %1 -U %2 -P %3 -d %4 -n -i "v8 stock labels insert sp.sql"
osql -S %1 -U %2 -P %3 -d %4 -n -i "v8 supplier insert sp.sql"
osql -S %1 -U %2 -P %3 -d %4 -n -i "v8 supplier profile insert sp.sql"
osql -S %1 -U %2 -P %3 -d %4 -n -i "v8 ward specialty link insert sp.sql"
osql -S %1 -U %2 -P %3 -d %4 -n -i "v8 wardstock list insert sp.sql"
osql -S %1 -U %2 -P %3 -d %4 -n -i "v8 wlabel insert sp.sql"
osql -S %1 -U %2 -P %3 -d %4 -n -i "v8 consultant specialty link insert sp.sql"
osql -S %1 -U %2 -P %3 -d %4 -n -i "v8 mediate insert sp.sql"
osql -S %1 -U %2 -P %3 -d %4 -n -i "v8 mediate archive insert sp.sql"
osql -S %1 -U %2 -P %3 -d %4 -n -i "v8 Formuia Insert sp.sql"
osql -S %1 -U %2 -P %3 -d %4 -n -i "v8 Layout Insert sp.sql"
osql -S %1 -U %2 -P %3 -d %4 -n -i "V8 Configuration Insert sp.sql"
osql -S %1 -U %2 -P %3 -d %4 -n -i "V8 PNproduct write sp.sql"
osql -S %1 -U %2 -P %3 -d %4 -n -i "V8 PNrule write sp.sql"
osql -S %1 -U %2 -P %3 -d %4 -n -i "V8 PNRulePrescriptionProforma Delete.sql"
osql -S %1 -U %2 -P %3 -d %4 -n -i "v8 wlookup insert sp.sql"
osql -S %1 -U %2 -P %3 -d %4 -n -i "v8 Conversion Tools Version.sql"
osql -S %1 -U %2 -P %3 -d %4 -n -i "v8 RichTextDocument Write sp.sql"
osql -S %1 -U %2 -P %3 -d %4 -n -i "v8 WPharmacyLog insert sp.sql"

echo "Finished"
