/*

   02 February 2005 10:20:30

   User: 

   Server: EDDIE-CRITCHLOW

   Database: v9-2-3_Testing

   Application: MS SQLEM - Data Tools

*/



BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET TRANSACTION ISOLATION LEVEL SERIALIZABLE
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
DROP INDEX sys.PersonAlias.IX_PersonAlias_Lookup
GO
CREATE UNIQUE NONCLUSTERED INDEX IX_PersonAlias_Lookup ON sys.PersonAlias
	(
	AliasGroupID,
	Forename,
	Surname,
	EntityID
	) WITH FILLFACTOR = 90 ON ENTITY
GO
COMMIT
